import json

"""
PRACTICE BANK GENERATOR — v2.0
Chuẩn DAC A5.D:
 - Vòng 1 (≥5 câu): Multiple Choice Fill-in-the-blank (Nhận biết công thức)
 - Vòng 2 (≥10 câu): Cloze context (5) + Error Identification (5) (Thông hiểu ngữ cảnh)
 - Vòng 3 (≥5 câu): Sentence Transformation (3) + Communication/Context MCQ (2) (Vận dụng cao)
"""

def mc(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"multiple_choice","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

def ei(stem, opts, correct, verdict, rule, why, trap, tip):
    """Error Identification"""
    return {"type":"error_identification","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

def st(stem, opts, correct, verdict, rule, why, trap, tip):
    """Sentence Transformation"""
    return {"type":"sentence_transformation","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

def comm(stem, opts, correct, verdict, rule, why, trap, tip):
    """Communication / Context MCQ"""
    return {"type":"communication","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

# ==================== CHAPTER 1: 12 TENSES ====================

# -------- TENSE 0: Hiện Tại Đơn (Present Simple) --------
tense_0 = {
  "round1": [
    mc("Hoàn thành câu: *\"The Earth ________ around the Sun.\"*<br>(Dịch: Trái Đất quay quanh Mặt Trời.)",
       {"A":"revolve","B":"revolves","C":"revolved","D":"revolving"}, "B",
       "**B: revolves**", "S (số ít) + V-s/es: Sự thật hiển nhiên.",
       "'The Earth' là số ít, 'revolve' thêm 's'.", "Dùng HTĐ đúng nhưng quên chia số ít.", "Chân lý vĩnh cửu → HTĐ + chia V theo ngôi."),
    mc("Hoàn thành câu: *\"She ________ her teeth twice a day.\"*<br>(Dịch: Cô ấy đánh răng hai lần một ngày.)",
       {"A":"brush","B":"brushes","C":"brushed","D":"is brushing"}, "B",
       "**B: brushes**", "Thói quen hằng ngày + chủ ngữ số ít → V-es.",
       "'Brush' kết thúc bằng -sh nên thêm -es.", "Thêm -s thay vì -es (brushs).", "Nhìn đuôi động từ: -sh/-ch/-s/-x/-z → thêm -es!"),
    mc("Hoàn thành câu: *\"They ________ English at school.\"*<br>(Dịch: Họ học tiếng Anh ở trường.)",
       {"A":"studies","B":"studying","C":"study","D":"studied"}, "C",
       "**C: study**", "S số nhiều (They) + V nguyên thể.",
       "'They' là số nhiều nên 'study' giữ nguyên, không thêm -ies.", "Nhầm They số ít → chọn 'studies'.", "They/We/I/You → V nguyên thể, không thêm -s!"),
    mc("Hoàn thành câu: *\"The museum ________ at 9 AM every day.\"*<br>(Dịch: Bảo tàng mở cửa lúc 9 giờ sáng mỗi ngày.)",
       {"A":"open","B":"opens","C":"opened","D":"is opening"}, "B",
       "**B: opens**", "Lịch trình cố định + số ít → V-s.",
       "'The museum' = It → 'opens'.", "Dùng tiếp diễn (is opening) cho lịch trình cố định.", "Lịch trình cố định → HTĐ!"),
    mc("Hoàn thành câu: *\"My cat ________ fish but ________ vegetables.\"*<br>(Dịch: Mèo tôi thích cá nhưng không thích rau.)",
       {"A":"like / doesn't like","B":"likes / don't like","C":"likes / doesn't like","D":"like / don't like"}, "C",
       "**C: likes / doesn't like**", "Số ít → likes; Phủ định số ít → doesn't like.",
       "Hai vế cùng chủ ngữ 'My cat' đều phải chia số ít.", "Bẫy: dùng 'don't' cho số ít hoặc 'like' không chia.", "Xác định chủ ngữ → chia đồng bộ cả khẳng định lẫn phủ định!"),
  ],
  "round2": [
    mc("Điền từ thích hợp vào chỗ trống:<br>*\"Water ________ at 100 degrees Celsius.\"*<br>(Dịch: Nước sôi ở 100 độ C.)",
       {"A":"boil","B":"boils","C":"is boiling","D":"boiled"}, "B",
       "**B: boils**", "Sự thật khoa học bất biến → HTĐ + chia số ít.",
       "'Water' là danh từ không đếm được, tương đương It → 'boils'.", "Nghĩ đang mô tả nước đang sôi → dùng HTTD (is boiling).", "Sự thật khoa học ≠ đang xảy ra → HTĐ!"),
    mc("Điền từ thích hợp vào chỗ trống:<br>*\"He usually ________ to work, but today he ________ the bus.\"*<br>(Dịch: Anh ấy thường đi bộ đến chỗ làm, nhưng hôm nay anh ấy đang đi xe buýt.)",
       {"A":"walks / takes","B":"walks / is taking","C":"walk / is taking","D":"is walking / takes"}, "B",
       "**B: walks / is taking**", "Thói quen → HTĐ; Hôm nay đang xảy ra → HTTD.",
       "'usually' → HTĐ (walks); 'today' + hành động đang diễn ra → HTTD (is taking).", "Chia đồng nhất cả 2 vế theo 'today'.", "Nhìn trạng từ của từng vế rồi chia riêng!"),
    mc("Điền từ thích hợp vào chỗ trống:<br>*\"I ________ you are right about this.\"*<br>(Dịch: Tôi nghĩ bạn đúng về điều này.)",
       {"A":"am thinking","B":"think","C":"thought","D":"thinks"}, "B",
       "**B: think**", "Động từ nhận thức (think/believe/know) không dùng tiếp diễn.",
       "'Think' ở đây là ý kiến/nhận thức → HTĐ.", "Thấy chủ ngữ 'I' nên dùng HTTD (am thinking).", "Think = ý kiến → HTĐ; Think = cân nhắc → HTTD!"),
    mc("Điền từ thích hợp vào chỗ trống:<br>*\"The next train to Hanoi ________ at 6 PM tomorrow.\"*<br>(Dịch: Chuyến tàu tiếp theo đến Hà Nội khởi hành lúc 6 giờ tối ngày mai.)",
       {"A":"will leave","B":"is leaving","C":"leaves","D":"left"}, "C",
       "**C: leaves**", "Lịch trình phương tiện công cộng → HTĐ dù có 'tomorrow'.",
       "Giờ chạy tàu là cố định, không thay đổi → HTĐ.", "Thấy 'tomorrow' → tự động dùng will/is going to.", "Tàu xe lịch trình → HTĐ; kế hoạch cá nhân → HTTD/will!"),
    mc("Điền từ thích hợp vào chỗ trống:<br>*\"She ________ always ________ her phone during class!\"*<br>(Dịch: Cô ấy cứ hay kiểm tra điện thoại trong lớp mãi! - phàn nàn)",
       {"A":"always checks","B":"is always checking","C":"always is checking","D":"always checked"}, "B",
       "**B: is always checking**", "HTTD + always = phàn nàn thói quen gây bực bội.",
       "Đây là câu than phiền về thói quen xấu, không phải mô tả thói quen thường xuyên.", "Thấy 'always' → HTĐ (always checks).", "Always + việc tiêu cực/bực bội → HTTD (is/am/are always V-ing)!"),
    ei("Câu sau có **một lỗi sai** duy nhất. Hãy chọn phương án **sửa đúng nhất**:<br>*\"My father don't drink coffee in the morning.\"*",
       {"A":"My father doesn't drink coffee in the morning.", "B":"My father don't drinks coffee in the morning.", "C":"My father doesn't drinks coffee in the morning.", "D":"My father isn't drinking coffee in the morning."}, "A",
       "**A** là câu đúng.", "Phủ định HTĐ số ít: S + **doesn't** + V-inf.",
       "'My father' = He → phải dùng 'doesn't', động từ 'drink' giữ nguyên.", "Sửa don't → doesn't nhưng thêm -s vào drink thành 'drinks' (phương án C).", "Đã có doesn't → động từ sau KHÔNG thêm -s!"),
    ei("Câu sau có **một lỗi sai** duy nhất. Hãy chọn phương án **sửa đúng nhất**:<br>*\"Does your sister lives in Da Nang?\"*",
       {"A":"Does your sister live in Da Nang?", "B":"Do your sister lives in Da Nang?", "C":"Is your sister live in Da Nang?", "D":"Does your sister lived in Da Nang?"}, "A",
       "**A** là câu đúng.", "Câu hỏi HTĐ: Does + S (số ít) + V-inf?",
       "Đã mượn 'Does' → động từ chính 'lives' phải trả về nguyên thể 'live'.", "Sửa 'Does' → 'Do' cho dù chủ ngữ là số ít (phương án B).", "Does/Doesn't mượn rồi → V sau đó = nguyên thể tuyệt đối!"),
    ei("Câu sau có **một lỗi sai** duy nhất. Hãy chọn phương án **sửa đúng nhất**:<br>*\"She go to the gym every Monday and Thursday.\"*",
       {"A":"She goes to the gym every Monday and Thursday.", "B":"She going to the gym every Monday and Thursday.", "C":"She is go to the gym every Monday and Thursday.", "D":"She gos to the gym every Monday and Thursday."}, "A",
       "**A** là câu đúng.", "S (số ít) + V-s/es: 'go' → 'goes'.",
       "Chủ ngữ 'She' yêu cầu động từ thêm -es (go → goes).", "Thêm -s thành 'gos' (phương án D) không đúng quy tắc chính tả.", "Đuôi -o → thêm -es: go→goes, do→does!"),
    ei("Câu sau có **một lỗi sai** duy nhất. Hãy chọn phương án **sửa đúng nhất**:<br>*\"Rarely she eats fast food.\"*",
       {"A":"She rarely eats fast food.", "B":"She rarely eat fast food.", "C":"Rarely does she eat fast food.", "D":"Cả A và C đều đúng."}, "D",
       "**D** là câu đúng — cả A lẫn C đều là cách viết đúng.", "Trạng từ tần suất đứng trước V thường; đảo ngữ 'Rarely does S V' cũng đúng.",
       "Cả hai cấu trúc đều hợp ngữ pháp: thường (A) và đảo ngữ văn viết (C).", "Nghĩ chỉ có 1 cách đúng.", "Rarely/Seldom/Hardly có thể gây đảo ngữ trong văn viết trang trọng!"),
    ei("Câu sau có **một lỗi sai** duy nhất. Hãy chọn phương án **sửa đúng nhất**:<br>*\"The news are very shocking today.\"*",
       {"A":"The news is very shocking today.", "B":"The new are very shocking today.", "C":"The news were very shocking today.", "D":"The news have been very shocking today."}, "A",
       "**A** là câu đúng.", "'News' tuy đuôi -s nhưng là danh từ số ít → động từ số ít 'is'.",
       "News/Mathematics/Physics/Economics = số ít → is/was.", "Nhìn đuôi -s → tự đoán số nhiều → dùng 'are'.", "News, maths, physics → luôn đi với động từ số ít!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** và đúng ngữ pháp nhất với câu sau:<br>*\"This is the first time Anna has visited Hoi An.\"*",
       {"A":"Anna visited Hoi An for the first time.", "B":"Anna has never visited Hoi An before.", "C":"Anna doesn't visit Hoi An often.", "D":"Anna first visited Hoi An last year."}, "B",
       "**B** là câu đồng nghĩa đúng.", "'First time + HTHT' = 'never + HTHT + before'.",
       "Lần đầu tiên tương đương với chưa bao giờ đến trước đây.", "Dùng QKĐ 'visited' mất đi tính liên hệ hiện tại.", "This is the first time S has V3 = S has never V3 before!"),
    st("Chọn câu **đồng nghĩa** và đúng ngữ pháp nhất với câu sau:<br>*\"It takes her 30 minutes to get to school every day.\"*",
       {"A":"She spends 30 minutes getting to school every day.", "B":"She takes 30 minutes to get to school every day.", "C":"Getting to school takes her every day 30 minutes.", "D":"She is taking 30 minutes to school every day."}, "A",
       "**A** là câu đồng nghĩa đúng.", "It takes sb time to do = S spends time V-ing.",
       "Cả hai cấu trúc cùng diễn đạt 'mất bao lâu để làm gì'.", "Dùng 'She takes 30 minutes...' sai cấu trúc (B).", "It takes sb time → S spends time doing!"),
    st("Chọn câu **đồng nghĩa** và đúng ngữ pháp nhất với câu sau:<br>*\"My brother is a student. He studies very hard.\"*<br>→ Viết lại thành 1 câu dùng mệnh đề quan hệ:",
       {"A":"My brother, who is a student, studies very hard.", "B":"My brother who studying very hard, is a student.", "C":"My brother, which is a student, studies very hard.", "D":"My brother studies very hard, he is a student."}, "A",
       "**A** là câu đúng.", "Mệnh đề quan hệ không hạn định (non-defining): who + V + dấu phẩy.",
       "'My brother' là người (who), thông tin thêm không xác định → dấu phẩy 2 bên.", "Dùng 'which' cho người (C).", "Người → who/whom; Vật → which; Người + Vật → that!"),
    comm("**Tình huống giao tiếp:** Nam hỏi Lan về thói quen mỗi sáng. Lan muốn nói: *'Mình thức dậy lúc 6 giờ sáng và ăn sáng trước khi đi học.'* Câu nào tự nhiên và đúng nhất?",
       {"A":"I woke up at 6 AM and ate breakfast before going to school.","B":"I wake up at 6 AM and eat breakfast before going to school.","C":"I'm waking up at 6 AM and eating breakfast before going to school.","D":"I will wake up at 6 AM and eat breakfast before going to school."}, "B",
       "**B** là đúng nhất.", "Thói quen hằng ngày → HTĐ.",
       "Đây là thói quen có tính lặp lại → HTĐ hoàn toàn phù hợp.", "Dùng QKĐ (A) vì sáng nay đã qua.", "Hỏi về thói quen → HTĐ, dù đang nói vào buổi chiều!"),
    comm("**Tình huống giao tiếp:** Hoa thấy bạn cùng phòng luôn bỏ quần áo bẩn lung tung, muốn phàn nàn một cách lịch sự. Câu nào đúng nhất?",
       {"A":"You always leave your dirty clothes on the floor!","B":"You are always leaving your dirty clothes on the floor!","C":"You always left your dirty clothes on the floor!","D":"You always are leaving your dirty clothes on the floor!"}, "B",
       "**B** là đúng nhất (HTTD + always = phàn nàn).", "HTTD + always = than phiền thói quen gây bực bội.",
       "Cấu trúc này được chọn khi 'always' đi với việc bực bội.", "Dùng HTĐ (A) không truyền tải được cảm xúc phàn nàn.", "Am/is/are ALWAYS V-ing = đang phàn nàn về thói quen xấu!"),
  ]
}

# -------- TENSE 1: Hiện Tại Tiếp Diễn (Present Continuous) --------
tense_1 = {
  "round1": [
    mc("Hoàn thành câu: *\"Look! It ________ heavily outside.\"*<br>(Dịch: Nhìn kìa! Bên ngoài đang mưa rất to.)",
       {"A":"rains","B":"rained","C":"is raining","D":"are raining"}, "C",
       "**C: is raining**", "HTTD: S + am/is/are + V-ing.",
       "'Look!' = hành động đang xảy ra ngay bây giờ; 'It' → 'is raining'.", "Dùng HTĐ 'rains' vì thấy thời tiết.", "Look!/Listen!/Watch! → HTTD!"),
    mc("Hoàn thành câu: *\"The students ________ quietly in the library now.\"*<br>(Dịch: Các học sinh đang đọc sách yên lặng trong thư viện lúc này.)",
       {"A":"are reading","B":"is reading","C":"reads","D":"reading"}, "A",
       "**A: are reading**", "Số nhiều (The students) + are + V-ing.",
       "'now' = đang diễn ra; 'The students' = số nhiều → 'are'.", "Quên to-be, chỉ dùng 'reading' (D).", "Phải có TO BE: am/is/are + V-ing!"),
    mc("Hoàn thành câu: *\"Be quiet! The baby ________.\"*<br>(Dịch: Yên nào! Em bé đang ngủ.)",
       {"A":"sleeps","B":"is sleeping","C":"are sleeping","D":"was sleeping"}, "B",
       "**B: is sleeping**", "Lệnh gây chú ý + hành động đang diễn ra → HTTD.",
       "'The baby' số ít → 'is sleeping'.", "Dùng QKĐ 'was sleeping' vì hiểu nhầm ngữ cảnh.", "Be quiet! / Ssh! / Look! → HTTD!"),
    mc("Hoàn thành câu: *\"We ________ to Paris next Friday. (kế hoạch chắc chắn)\"*<br>(Dịch: Chúng tôi sẽ bay đến Paris vào thứ Sáu tới.)",
       {"A":"fly","B":"will fly","C":"are flying","D":"flew"}, "C",
       "**C: are flying**", "HTTD diễn tả kế hoạch cá nhân đã sắp xếp sẵn.",
       "Vé đã mua, lịch đã fix → kế hoạch chắc chắn → HTTD.", "Dùng 'will fly' (quyết định bộc phát, không phải kế hoạch).", "Kế hoạch đã có sắp xếp → HTTD; Quyết định tức thì → Will!"),
    mc("Hoàn thành câu: *\"I ________ (not/feel) well today, so I'll stay home.\"*<br>(Dịch: Tôi không cảm thấy khỏe hôm nay, nên tôi sẽ ở nhà.)",
       {"A":"don't feel","B":"am not feeling","C":"isn't feeling","D":"not feel"}, "B",
       "**B: am not feeling**", "HTTD diễn tả trạng thái tạm thời ngay lúc này.",
       "Cảm giác hôm nay (tạm thời, không phải thói quen) → HTTD.", "Dùng HTĐ 'don't feel' vì 'feel' là động từ trạng thái.", "Feel đôi khi dùng HTTD khi chỉ cảm giác thể chất tạm thời!"),
  ],
  "round2": [
    mc("Điền từ đúng vào chỗ trống:<br>*\"Tom can't come to the phone right now. He ________ a shower.\"*",
       {"A":"has","B":"is having","C":"have","D":"had"}, "B",
       "**B: is having**", "HTTD: hành động đang diễn ra ngay lúc được hỏi.",
       "'right now' + đang làm việc gì đó → HTTD. 'He' → 'is having'.", "Dùng 'has' vì 'have' là động từ trạng thái.", "Have = sở hữu → HTĐ; Have a shower/meal = hành động → HTTD!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"More and more people ________ electric cars these days.\"*<br>(Dịch: Ngày càng nhiều người đang mua xe điện trong thời gian gần đây.)",
       {"A":"buy","B":"are buying","C":"bought","D":"buys"}, "B",
       "**B: are buying**", "Xu hướng đang thay đổi trong thời gian hiện tại → HTTD.",
       "'These days' = xu hướng hiện tại đang thay đổi → HTTD.", "Dùng HTĐ 'buy' vì không thấy 'now'.", "These days/Nowadays/Currently → HTTD (xu hướng hiện tại)!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"I ________ what you mean. Please explain more clearly.\"*<br>(Dịch: Tôi không hiểu ý bạn muốn nói gì. Vui lòng giải thích rõ hơn.)",
       {"A":"am not understanding","B":"don't understand","C":"wasn't understanding","D":"doesn't understand"}, "B",
       "**B: don't understand**", "Động từ nhận thức (understand) = State Verb → không dùng tiếp diễn.",
       "'Understand' chỉ trạng thái nhận thức, tuyệt đối không thêm -ing.", "Nghĩ hành động đang diễn ra → am not understanding.", "Understand/know/believe/love → KHÔNG bao giờ dùng -ing!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"A: What ________ tonight? B: Nothing special.\"*<br>(Dịch: Bạn có kế hoạch gì tối nay không? - Không có gì đặc biệt.)",
       {"A":"do you do","B":"are you doing","C":"did you do","D":"will you do"}, "B",
       "**B: are you doing**", "Hỏi về kế hoạch tương lai gần → HTTD câu hỏi.",
       "'Tonight' = tương lai gần, hỏi xem có plan gì không → HTTD.", "Dùng 'do you do' (HTĐ) hỏi thói quen chứ không hỏi tối nay.", "Hỏi kế hoạch tối nay/cuối tuần → HTTD!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"He ________ better since he started taking medicine.\"*<br>(Dịch: Anh ấy đang hồi phục tốt hơn kể từ khi bắt đầu uống thuốc.)",
       {"A":"is getting","B":"gets","C":"get","D":"got"}, "A",
       "**A: is getting**", "Get = trở nên: diễn tả sự thay đổi đang diễn ra → HTTD.",
       "Get/grow/become + tính ngữ = sự thay đổi → HTTD.", "Dùng HTĐ 'gets' không nắm bắt được tính tiến triển.", "Get better/worse/bigger/taller → HTTD (đang thay đổi)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She is knowing the answer to every question.\"*",
       {"A":"She knows the answer to every question.","B":"She is know the answer to every question.","C":"She was knowing the answer to every question.","D":"She have known the answer to every question."}, "A",
       "**A** là câu đúng.", "'Know' = State Verb → tuyệt đối không dùng tiếp diễn.",
       "Know chỉ trạng thái, không phải hành động đang làm → HTĐ.", "Sửa sang thì khác nhưng vẫn giữ -ing.", "Know/see/hear/want/need → KHÔNG bao giờ là -ing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Look at those clouds. It will rain soon.\"*",
       {"A":"Look at those clouds. It is going to rain soon.","B":"Look at those clouds. It rains soon.","C":"Look at those clouds. It was raining soon.","D":"Look at those clouds. It has rained soon."}, "A",
       "**A** là câu đúng.", "Bằng chứng hiện tại (mây đen) → Dự đoán có căn cứ = be going to.",
       "Thấy mây đen trước mắt → bằng chứng → 'is going to rain'.", "Dùng 'will' khi không có bằng chứng rõ ràng.", "Bằng chứng rõ = be going to; Phỏng đoán mơ hồ = will!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"They are play football in the park at the moment.\"*",
       {"A":"They are playing football in the park at the moment.","B":"They play football in the park at the moment.","C":"They playing football in the park at the moment.","D":"They is playing football in the park at the moment."}, "A",
       "**A** là câu đúng.", "HTTD bắt buộc: to be + V-ing (không được bỏ qua -ing).",
       "'are play' thiếu -ing → sai hoàn toàn.", "Dùng 'They is' (sai hòa hợp chủ-vị).", "To be + V + -ing = bộ đôi bất khả phân!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I am haveing a great time at the party.\"*",
       {"A":"I am having a great time at the party.","B":"I have a great time at the party.","C":"I is having a great time at the party.","D":"I are having a great time at the party."}, "A",
       "**A** là câu đúng.", "Quy tắc chính tả: have → drop -e → adding.",
       "Động từ kết thúc bằng -e câm → bỏ -e trước khi thêm -ing.", "Giữ nguyên 'haveing' (lỗi chính tả).", "V kết thúc -e câm → bỏ e + ing: have→having, make→making!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"My parents are owning a big house in the countryside.\"*",
       {"A":"My parents own a big house in the countryside.","B":"My parents is owning a big house in the countryside.","C":"My parents was owning a big house in the countryside.","D":"My parents are owned a big house in the countryside."}, "A",
       "**A** là câu đúng.", "'Own' = động từ sở hữu (State Verb) → HTĐ.",
       "Own/belong/possess chỉ tình trạng sở hữu → không dùng -ing.", "Giữ 'are owning' vì thấy 'are'.", "Own/belong/possess → KHÔNG dùng -ing!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"My plan is to study abroad next year.\"*",
       {"A":"I am studying abroad next year.","B":"I will study abroad next year.","C":"I have studied abroad next year.","D":"I studied abroad next year."}, "A",
       "**A** là đúng nhất.", "Kế hoạch cá nhân đã định → HTTD.",
       "HTTD có thể diễn đạt kế hoạch cá nhân đã lên = plan is to do.", "Dùng 'will' (quyết định mới).", "My plan is to do = I am doing (HTTD)!"),
    st("Chọn câu **sắp xếp đúng** trật tự từ:<br>*[constantly / He / late / is / being / for meetings]*",
       {"A":"He is constantly being late for meetings.","B":"He constantly is being late for meetings.","C":"He is being constantly late for meetings.","D":"He is late constantly being for meetings."}, "A",
       "**A** là câu đúng.", "Trạng từ tần suất đứng sau to be (is constantly V-ing).",
       "'constantly' + hành động gây bực bội → HTTD.", "Đặt 'constantly' trước 'is'.", "To be + trạng từ + V-ing!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"It's noisy because the neighbors are having a party.\"*",
       {"A":"The neighbors, who are having a party, make it noisy.","B":"The neighbors are having a party, so it's noisy.","C":"It's noisy, however the neighbors are having a party.","D":"The neighbors have a party, then it was noisy."}, "B",
       "**B** là đúng nhất (quan hệ nguyên nhân-kết quả).", "Dùng 'so' để nối nguyên nhân → kết quả.",
       "Party → noise: nguyên nhân trước kết quả sau, dùng 'so'.", "Dùng 'however' (tương phản) sai quan hệ logic.", "Because → kết quả; So → kết quả từ nguyên nhân vừa nêu!"),
    comm("**Tình huống:** Bạn gọi điện cho giáo viên, thầy bảo 'One moment please.' Sau đó bạn muốn hỏi: 'Thầy đang bận không?' Câu nào tự nhiên nhất?",
       {"A":"Are you busy now, sir?","B":"Do you busy now, sir?","C":"Were you busy, sir?","D":"Have you been busy, sir?"}, "A",
       "**A** là tự nhiên nhất.", "Hỏi trạng thái đang xảy ra → HTTD (Are you V-ing/adj).",
       "'Are you busy?' hỏi trạng thái hiện tại → chuẩn.", "Dùng 'Do you busy' sai cấu trúc.", "Hỏi trạng thái hiện tại → Are/Is + S + adj?"),
    comm("**Tình huống:** Bạn thấy một người lạ đang nhìn vào bản đồ và có vẻ bối rối. Bạn muốn hỏi xem họ có cần giúp không. Câu nào lịch sự nhất?",
       {"A":"Are you looking for something?","B":"Do you look for something?","C":"Did you look for something?","D":"You are looking for something?"}, "A",
       "**A** là lịch sự và tự nhiên nhất.", "HTTD diễn tả điều đang xảy ra ngay trước mắt.",
       "Người đó đang nhìn bản đồ ngay lúc này → HTTD.", "Dùng HTĐ 'Do you look for' hỏi về thói quen.", "Thấy ai đang làm gì → dùng HTTD để hỏi!"),
  ]
}

# -------- TENSE 2: Hiện Tại Hoàn Thành (Present Perfect) --------
tense_2 = {
  "round1": [
    mc("Hoàn thành câu: *\"She ________ to Japan three times.\"*<br>(Dịch: Cô ấy đã đến Nhật Bản ba lần.)",
       {"A":"has been","B":"have been","C":"was","D":"has gone"}, "A",
       "**A: has been**", "HTHT: S (số ít) + has + V3 (been = trải nghiệm đã về).",
       "'She' = số ít → 'has'; 'been to' = đã đến và đã về.", "Dùng 'has gone to' (đang ở đó, chưa về).", "Been to = đã đến rồi về; Gone to = đã đi chưa về!"),
    mc("Hoàn thành câu: *\"I ________ seen that movie yet.\"*<br>(Dịch: Tôi vẫn chưa xem bộ phim đó.)",
       {"A":"have not","B":"has not","C":"haven't never","D":"didn't"}, "A",
       "**A: have not**", "Phủ định HTHT: S (I) + have not + V3.",
       "'yet' trong câu phủ định = chưa; 'I' → 'have not'.", "Dùng 'didn't' (QKĐ không dùng được với 'yet' phủ định).", "Haven't + V3 + yet = chưa làm gì đó!"),
    mc("Hoàn thành câu: *\"________ you ever ________ sushi?\"*<br>(Dịch: Bạn đã từng ăn sushi bao giờ chưa?)",
       {"A":"Have / eaten","B":"Did / eat","C":"Have / eat","D":"Has / eaten"}, "A",
       "**A: Have / eaten**", "Câu hỏi HTHT: Have + S + ever + V3?",
       "'ever' trong câu hỏi = đã từng; 'you' → 'Have'; V3 của 'eat' = 'eaten'.", "Dùng 'Did' (QKĐ không đi được với 'ever' theo kiểu này).", "Have/Has + S + ever + V3? → hỏi trải nghiệm!"),
    mc("Hoàn thành câu: *\"They ________ here for ten years.\"*<br>(Dịch: Họ đã sống ở đây được mười năm.)",
       {"A":"lived","B":"have lived","C":"lives","D":"are living"}, "B",
       "**B: have lived**", "HTHT: kéo dài từ quá khứ đến hiện tại với 'for'.",
       "'for ten years' + kéo dài đến nay → HTHT.", "Dùng QKĐ 'lived' (kết thúc hoàn toàn, không liên hệ hiện tại).", "For + khoảng thời gian (liên hệ hiện tại) → HTHT!"),
    mc("Hoàn thành câu: *\"The match has ________ started. We missed the beginning.\"*<br>(Dịch: Trận đấu đã bắt đầu rồi. Chúng ta đã lỡ phần đầu.)",
       {"A":"already","B":"yet","C":"ever","D":"never"}, "A",
       "**A: already**", "'Already' dùng trong câu khẳng định HTHT = đã rồi.",
       "Câu khẳng định + HTHT + 'already' = đã xảy ra trước dự kiến.", "Dùng 'yet' (câu phủ định/câu hỏi).", "Already = đã rồi (khẳng định); Yet = chưa/chưa chưa (phủ định/câu hỏi)!"),
  ],
  "round2": [
    mc("Điền từ đúng vào chỗ trống:<br>*\"It's the most beautiful painting I ________ ever seen.\"*<br>(Dịch: Đây là bức tranh đẹp nhất mà tôi từng thấy.)",
       {"A":"have","B":"had","C":"has","D":"was"}, "A",
       "**A: have**", "Cấu trúc: It's the + superlative + S + have ever + V3.",
       "Sau so sánh tuyệt đối + ever → HTHT.", "Dùng 'had' (QKHT - sai thì).", "Superlative + ever → HTHT (have/has + V3)!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"I ________ her since she moved to Saigon.\"*<br>(Dịch: Tôi chưa gặp cô ấy kể từ khi cô ấy chuyển vào Sài Gòn.)",
       {"A":"didn't see","B":"haven't seen","C":"don't see","D":"hadn't seen"}, "B",
       "**B: haven't seen**", "Since + mốc QK → HTHT kéo dài đến hiện tại.",
       "'since she moved' là mốc thời gian → kéo dài đến nay → HTHT.", "Dùng QKĐ 'didn't see' (kết thúc, không liên hệ hiện tại).", "Since + mốc QK → HTHT! Đây là nguyên tắc vàng!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"The scientists ________ a new vaccine for the disease.\"*<br>(Dịch: Các nhà khoa học vừa phát triển được một loại vaccine mới.)",
       {"A":"just developed","B":"have just developed","C":"just develop","D":"just have developed"}, "B",
       "**B: have just developed**", "Just + HTHT = vừa mới làm gì xong.",
       "'just' đứng giữa have/has và V3.", "Dùng QKĐ 'just developed' (thiếu liên hệ kết quả hiện tại).", "Just đứng sau have/has, TRƯỚC V3!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"A: Have you finished the report? B: No, not ________.\"*<br>(Dịch: Bạn hoàn thành báo cáo chưa? - Chưa.)",
       {"A":"already","B":"ever","C":"yet","D":"just"}, "C",
       "**C: yet**", "'Yet' trong câu trả lời phủ định = chưa.",
       "Trả lời 'Not yet' = chưa xong.", "Dùng 'already' (câu khẳng định).", "Not yet = chưa; Already = đã rồi!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"We ________ our homework, so now we can watch TV.\"*<br>(Dịch: Chúng tôi đã làm xong bài tập rồi, nên bây giờ có thể xem TV.)",
       {"A":"finished","B":"have finished","C":"finish","D":"had finished"}, "B",
       "**B: have finished**", "HTHT: Kết quả của hành động quá khứ ảnh hưởng đến hiện tại.",
       "Làm xong (quá khứ) → có thể xem TV (hiện tại) → HTHT.", "Dùng QKĐ 'finished' (không nhấn mạnh kết quả hiện tại).", "Hành động QK có kết quả ở hiện tại → HTHT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She has lived in Hanoi since five years.\"*",
       {"A":"She has lived in Hanoi for five years.","B":"She lived in Hanoi since five years.","C":"She has been living in Hanoi since five years ago.","D":"She has lived in Hanoi in five years."}, "A",
       "**A** là câu đúng.", "For + khoảng thời gian; Since + mốc thời gian.",
       "'Five years' là khoảng thời gian → phải dùng 'for'.", "Sửa bằng cách thêm 'ago' giữ 'since' (C).", "Khoảng thời gian → FOR; Mốc thời gian → SINCE!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He has went to the market this morning.\"*",
       {"A":"He has gone to the market this morning.","B":"He went to the market this morning.","C":"He have gone to the market this morning.","D":"He go to the market this morning."}, "B",
       "**B** là câu đúng nhất.", "'This morning' có thể ám chỉ đã qua → QKĐ phù hợp hơn.",
       "Nếu buổi sáng đã kết thúc → QKĐ 'went'; 'went' = V2 đúng, không phải 'went' sau has.", "Giữ HTHT nhưng sửa 'went' → 'gone' (A) — cũng chấp nhận được.", "Khi mốc thời gian rõ ràng đã qua → QKĐ! (this morning nếu đã chiều/tối)"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Did you finish your homework yet?\"*",
       {"A":"Have you finished your homework yet?","B":"Do you finish your homework yet?","C":"Had you finished your homework yet?","D":"Were you finishing your homework yet?"}, "A",
       "**A** là câu đúng.", "Câu hỏi có 'yet' → HTHT.",
       "'Yet' trong câu hỏi yêu cầu HTHT, không phải QKĐ.", "Dùng QKHT 'Had you' (câu hỏi về QKHT).", "Yet trong câu hỏi → Have/Has S + V3?"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I have seen him yesterday at the mall.\"*",
       {"A":"I saw him yesterday at the mall.","B":"I have saw him yesterday at the mall.","C":"I had seen him yesterday at the mall.","D":"I see him yesterday at the mall."}, "A",
       "**A** là câu đúng.", "'Yesterday' = mốc QK cụ thể → QKĐ.",
       "HTHT không dùng với mốc thời gian xác định trong QK (yesterday, last week, in 2020...).", "Dùng QKHT 'had seen' (C).", "Yesterday/Last week/In 2020 → QKĐ, không bao giờ là HTHT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"They have been married since 20 years.\"*",
       {"A":"They have been married for 20 years.","B":"They are married since 20 years.","C":"They married for 20 years.","D":"They were married since 20 years."}, "A",
       "**A** là câu đúng.", "For + khoảng thời gian (20 years = khoảng).",
       "20 years là khoảng thời gian → 'for', không phải 'since'.", "Đổi cả thì sang QKĐ/HTĐ (C, B).", "20 years = khoảng → FOR!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"This is the first time I have eaten pho.\"*",
       {"A":"I have never eaten pho before.","B":"I eat pho for the first time.","C":"I ate pho and it was the first time.","D":"I haven't eaten pho ever."}, "A",
       "**A** là đúng nhất.", "This is the first time S has V3 = S has never V3 before.",
       "Lần đầu tiên ăn = chưa bao giờ ăn trước đây.", "Dùng QKĐ (C) mất tính liên hệ hiện tại.", "First time + HTHT = Never + HTHT + before!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She started working here 3 years ago and she still works here.\"*",
       {"A":"She has worked here for 3 years.","B":"She worked here for 3 years.","C":"She has been working here since 3 years.","D":"She works here since 3 years ago."}, "A",
       "**A** là đúng nhất.", "Bắt đầu QK + còn tiếp tục → HTHT + for.",
       "Kéo dài từ 3 năm trước đến nay → HTHT + for 3 years.", "Dùng QKĐ 'worked' (C) ngụ ý đã nghỉ rồi.", "Bắt đầu QK + vẫn còn → HTHT (for/since)!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The last time they met was in 2022.\"*",
       {"A":"They haven't met since 2022.","B":"They didn't meet since 2022.","C":"They have met in 2022.","D":"They haven't met for 2022."}, "A",
       "**A** là đúng nhất.", "Last time + QKĐ → Haven't + V3 + since mốc đó.",
       "Lần gặp cuối 2022 → từ 2022 đến nay chưa gặp → haven't met since 2022.", "Dùng 'for 2022' (since mới đi với mốc thời gian).", "Last time + QKĐ (năm X) = Haven't V3 since X!"),
    comm("**Tình huống:** Bạn về đến nhà, mẹ hỏi 'Con ăn tối chưa?' Bạn muốn nói 'Rồi ạ, con vừa ăn xong.' Câu nào đúng và tự nhiên nhất?",
       {"A":"Yes, I have already eaten.","B":"Yes, I already ate.","C":"Yes, I just ate dinner.","D":"Cả A và C đều đúng."}, "D",
       "**D** là đúng — cả A lẫn C đều chấp nhận được.", "HTHT (A) nhấn mạnh kết quả; QKĐ (C) tự nhiên trong giao tiếp.",
       "Trong tiếng Anh thực tế, cả hai đều được dùng tùy vùng.", "Chỉ chấp nhận một đáp án.", "HTHT = British English chuẩn; QKĐ = phổ biến trong American English!"),
    comm("**Tình huống:** Bạn muốn kể cho người bạn mới quen về những nơi bạn đã từng đến. Câu mở đầu nào hay nhất?",
       {"A":"I have visited many interesting places around the world.","B":"I visited many interesting places around the world.","C":"I visit many interesting places around the world.","D":"I was visiting many interesting places around the world."}, "A",
       "**A** là tự nhiên nhất để nói về trải nghiệm tích lũy.", "HTHT diễn tả trải nghiệm tích lũy (chưa chỉ rõ thời điểm).",
       "Nói về trải nghiệm nói chung → HTHT.", "Dùng QKĐ (B) khi muốn nói đến một chuyến đi cụ thể.", "Trải nghiệm tổng quát (không rõ mốc thời gian) → HTHT!"),
  ]
}

# -------- TENSE 3: Quá Khứ Đơn (Past Simple) --------
tense_3 = {
  "round1": [
    mc("Hoàn thành câu: *\"She ________ a new dress for the party last Saturday.\"*<br>(Dịch: Cô ấy đã mua một chiếc váy mới cho bữa tiệc thứ Bảy tuần trước.)",
       {"A":"buys","B":"buy","C":"bought","D":"was buying"}, "C",
       "**C: bought**", "QKĐ: 'buy' → V2 = 'bought' (bất quy tắc); last Saturday = mốc QK.",
       "Dấu hiệu 'last Saturday' → QKĐ; 'buy' bất quy tắc → 'bought'.", "Thêm -ed thành 'buyed' (sai vì bất quy tắc).", "Last + thời gian → QKĐ! Học bảng bất quy tắc!"),
    mc("Hoàn thành câu: *\"________ you ________ to the concert last night?\"*<br>(Dịch: Bạn có đi dự buổi hòa nhạc tối qua không?)",
       {"A":"Did / go","B":"Do / go","C":"Did / went","D":"Have / gone"}, "A",
       "**A: Did / go**", "Câu hỏi QKĐ: Did + S + V-inf?",
       "'last night' = QK; 'Did' mượn → V chính 'go' giữ nguyên.", "Dùng 'Did / went' (hai lần chia QK).", "Did mượn → V sau = nguyên thể, không thêm -ed!"),
    mc("Hoàn thành câu: *\"The movie ________ two hours ago.\"*<br>(Dịch: Bộ phim đã kết thúc cách đây hai tiếng.)",
       {"A":"end","B":"ends","C":"ended","D":"has ended"}, "C",
       "**C: ended**", "ago = mốc QK xác định → QKĐ; end + ed.",
       "Dấu hiệu 'ago' → QKĐ; 'end' có quy tắc → thêm -ed.", "Dùng HTHT 'has ended' với 'ago' (sai).", "Ago luôn đi với QKĐ, KHÔNG bao giờ là HTHT!"),
    mc("Hoàn thành câu: *\"We ________ a fantastic holiday in Phu Quoc in 2023.\"*<br>(Dịch: Chúng tôi đã có một kỳ nghỉ tuyệt vời ở Phú Quốc năm 2023.)",
       {"A":"had","B":"have","C":"have had","D":"are having"}, "A",
       "**A: had**", "In 2023 = mốc QK cụ thể → QKĐ; have → V2 = had.",
       "Năm 2023 đã qua, đây là mốc thời gian rõ ràng → QKĐ.", "Dùng HTHT 'have had' với 'in 2023' (sai).", "In + năm đã qua → QKĐ!"),
    mc("Hoàn thành câu: *\"He ________ his wallet, so he couldn't pay for dinner.\"*<br>(Dịch: Anh ấy đã để quên ví, nên không thể trả tiền bữa tối.)",
       {"A":"forget","B":"forgot","C":"forgotten","D":"was forgetting"}, "B",
       "**B: forgot**", "Chuỗi sự kiện trong QK; forget → V2 = forgot.",
       "Hai hành động đều trong QK, đơn → QKĐ; 'forget' bất quy tắc → 'forgot'.", "Dùng 'forgotten' (V3, cần have trước).", "Forget → Forgot → Forgotten (V1-V2-V3)!"),
  ],
  "round2": [
    mc("Điền từ đúng vào chỗ trống:<br>*\"When I ________ home, my sister ________ TV.\"*<br>(Dịch: Khi tôi về nhà, chị tôi đang xem TV.)",
       {"A":"arrived / watched","B":"arrived / was watching","C":"was arriving / was watching","D":"arrive / was watching"}, "B",
       "**B: arrived / was watching**", "QKĐ xen vào hành động QKTD đang diễn ra.",
       "Về nhà (đột ngột) → QKĐ; Đang xem TV (đang diễn ra khi về) → QKTD.", "Dùng QKĐ cho cả 2 (watched) — mất tính đang diễn ra.", "Khi (When) QKĐ xen vào QKTD đang diễn ra!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"She ________ the whole cake by herself! I can't believe it.\"*<br>(Dịch: Cô ấy đã ăn hết cả cái bánh một mình! Tôi không thể tin được.)",
       {"A":"eat","B":"eats","C":"ate","D":"eaten"}, "C",
       "**C: ate**", "Hành động đã xảy ra và hoàn toàn kết thúc; eat → V2 = ate.",
       "Hành động đã xong hẳn → QKĐ; 'eat' bất quy tắc → 'ate'.", "Dùng 'eaten' (V3 cần have trước).", "Eat → Ate → Eaten!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"The police ________ the thief after a 30-minute chase.\"*<br>(Dịch: Cảnh sát đã bắt được tên trộm sau 30 phút đuổi theo.)",
       {"A":"catched","B":"catch","C":"caught","D":"was catching"}, "C",
       "**C: caught**", "Sự kiện QK hoàn tất; catch → V2 = caught (bất quy tắc).",
       "After + khoảng thời gian trong QK → QKĐ; catch bất quy tắc → caught.", "Thêm -ed thành 'catched' (sai - bất quy tắc).", "Catch → Caught → Caught!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"I ________ her three times but she ________ up.\"*<br>(Dịch: Tôi đã gọi cô ấy ba lần nhưng cô ấy không bắt máy.)",
       {"A":"called / didn't pick","B":"called / doesn't pick","C":"called / wasn't picking","D":"have called / didn't pick"}, "A",
       "**A: called / didn't pick**", "Chuỗi hành động trong QK → QKĐ cho cả 2 vế.",
       "Gọi điện và bắt máy đều là QKĐ rõ ràng.", "Dùng phủ định HTĐ 'doesn't pick' (B).", "QKĐ + and/but + QKĐ = chuỗi sự kiện quá khứ!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"The company ________ in 1998 by two university students.\"*<br>(Dịch: Công ty được thành lập vào năm 1998 bởi hai sinh viên đại học.)",
       {"A":"found","B":"was founded","C":"has been founded","D":"is founded"}, "B",
       "**B: was founded**", "Bị động QKĐ: was/were + V3 + by + tác nhân.",
       "In 1998 = mốc QK; công ty không tự thành lập → bị động QKĐ.", "Dùng 'found' (V2 của 'find', không phải của 'found').", "In + năm QK + bị động → was/were + V3!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Yesterday, she goed to the market early in the morning.\"*",
       {"A":"Yesterday, she went to the market early in the morning.","B":"Yesterday, she goes to the market early in the morning.","C":"Yesterday, she has gone to the market early in the morning.","D":"Yesterday, she go to the market early in the morning."}, "A",
       "**A** là câu đúng.", "go → V2 = went (bất quy tắc, không phải 'goed').",
       "Yesterday + QKĐ; go bất quy tắc → went.", "Thêm -ed thành 'goed' (sai).", "Go → Went! Không có 'goed' trong tiếng Anh!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Where did you went last summer?\"*",
       {"A":"Where did you go last summer?","B":"Where were you went last summer?","C":"Where you went last summer?","D":"Where have you went last summer?"}, "A",
       "**A** là câu đúng.", "Did + V-inf: 'went' phải trở về 'go'.",
       "Did đã mượn trợ từ → V chính trả về nguyên thể 'go'.", "Dùng 'were you went' (lỗi pha trộn to be với V thường).", "Did mượn → V sau = nguyên thể tuyệt đối!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I have seen him at the party last Friday.\"*",
       {"A":"I saw him at the party last Friday.","B":"I have see him at the party last Friday.","C":"I seed him at the party last Friday.","D":"I am seeing him at the party last Friday."}, "A",
       "**A** là câu đúng.", "'Last Friday' = mốc QK xác định → QKĐ, không phải HTHT.",
       "HTHT không dùng với 'last + thời gian'.", "Giữ 'have seen' vì tưởng đây là trải nghiệm (C).", "Last Friday/yesterday/in 2020 → QKĐ, tuyệt đối không HTHT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"The children didn't enjoyed the horror movie.\"*",
       {"A":"The children didn't enjoy the horror movie.","B":"The children didn't enjoyed the horror movie.","C":"The children doesn't enjoy the horror movie.","D":"The children aren't enjoying the horror movie."}, "A",
       "**A** là câu đúng.", "didn't + V-inf: 'enjoyed' → 'enjoy'.",
       "Đã có 'didn't' (trợ động từ) → động từ chính về nguyên thể.", "Giữ 'enjoyed' vì nghĩ cần QKĐ (B).", "Didn't mượn rồi → V nguyên thể, không -ed!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She was very tire after the long journey.\"*",
       {"A":"She was very tired after the long journey.","B":"She is very tired after the long journey.","C":"She were very tired after the long journey.","D":"She was very tiring after the long journey."}, "A",
       "**A** là câu đúng.", "tired = mệt (tính từ của người); tire là động từ.",
       "Cần tính từ sau 'very': 'tired' (cảm thấy mệt) là đúng.", "Dùng 'tiring' (gây mệt, tính từ của vật).", "Tired = người cảm thấy mệt; Tiring = vật gây ra sự mệt mỏi!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She didn't eat anything because she was on a diet.\"*",
       {"A":"She ate nothing as she was dieting.","B":"She didn't eat nothing because she was on a diet.","C":"She wasn't eating anything, however she was on a diet.","D":"She ate nothing, so she was on a diet."}, "A",
       "**A** là đúng nhất.", "didn't eat anything = ate nothing; because = as (lý do).",
       "Phủ định kép 'didn't eat nothing' sai ngữ pháp tiếng Anh.", "Dùng 'however' (tương phản) sai logic.", "Didn't eat anything = Ate nothing (phủ định + bất định = phủ định tuyệt đối)!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"Tom started working at 7 AM and finished at 5 PM.\"*",
       {"A":"Tom worked from 7 AM to 5 PM.","B":"Tom was working from 7 AM to 5 PM.","C":"Tom works from 7 AM to 5 PM.","D":"Tom had worked from 7 AM to 5 PM."}, "A",
       "**A** là đúng nhất.", "Start + QKĐ và finish + QKĐ → QKĐ from...to...",
       "Hai hành động liên tiếp hoàn tất → tóm gọn bằng from...to...", "Dùng QKTD 'was working' (đang diễn ra, không phải kết thúc).", "Start...to finish = from...to (QKĐ)!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The last time I called her was two months ago.\"*",
       {"A":"I haven't called her for two months.","B":"I called her since two months.","C":"I haven't called her since two months.","D":"I didn't call her for two months."}, "A",
       "**A** là đúng nhất.", "Last time + QKĐ (2 months ago) → Haven't + V3 + for 2 months.",
       "Khoảng thời gian 'two months' → 'for'; liên hệ hiện tại → HTHT.", "Dùng 'since two months' (sai giới từ cho khoảng thời gian).", "Last time + ago = Haven't V3 + for (khoảng)!"),
    comm("**Tình huống:** Bạn đang kể chuyến đi Đà Lạt tuần trước. Câu mở đầu nào tự nhiên nhất?",
       {"A":"I went to Da Lat last week and it was amazing!","B":"I have gone to Da Lat last week and it was amazing!","C":"I go to Da Lat last week and it is amazing!","D":"I had gone to Da Lat last week and it was amazing!"}, "A",
       "**A** là tự nhiên nhất.", "Sự kiện QK với mốc thời gian rõ 'last week' → QKĐ.",
       "Kể chuyện đã xảy ra → QKĐ; 'last week' là mốc → càng phải QKĐ.", "Dùng HTHT 'have gone' với 'last week' (sai).", "Last week/yesterday/in 2023 → QKĐ khi kể chuyện!"),
    comm("**Tình huống:** Bạn muốn hỏi người bạn xem họ thích bộ phim tối qua không. Câu nào đúng?",
       {"A":"Did you like the movie last night?","B":"Do you like the movie last night?","C":"Have you liked the movie last night?","D":"Were you liking the movie last night?"}, "A",
       "**A** là đúng.", "Hỏi về cảm nhận sự kiện QK cụ thể 'last night' → QKĐ.",
       "'Last night' = mốc QK → Did + S + V-inf?", "Dùng HTĐ (B) hỏi thói quen.", "Mốc QK rõ ràng → Did...?"),
  ]
}

# Build the full dictionary
PRACTICE_BANK = {
    "tense_0": tense_0,
    "tense_1": tense_1,
    "tense_2": tense_2,
    "tense_3": tense_3,
}

# Write to file
output_path = '/Users/danghong/Documents/Exam Runners/website/js/practice_bank.js'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED PRACTICE BANK v2.0 — Chuẩn DAC A5.D\n')
    f.write('// Vòng 1: ≥5 câu Multiple Choice | Vòng 2: ≥10 câu (Cloze + Error ID) | Vòng 3: ≥5 câu (Transformation + Communication)\n')
    f.write(f'const PRACTICE_BANK = {json.dumps(PRACTICE_BANK, indent=2, ensure_ascii=False)};\n')

print(f"Done. Keys: {list(PRACTICE_BANK.keys())}")
for k, v in PRACTICE_BANK.items():
    print(f"  {k}: R1={len(v['round1'])}, R2={len(v['round2'])}, R3={len(v['round3'])}")
