import json

with open('/Users/danghong/Documents/Exam Runners/website/js/practice_bank.js', 'r', encoding='utf-8') as f:
    content = f.read()
idx = content.index('const PRACTICE_BANK = ') + len('const PRACTICE_BANK = ')
end_idx = content.rindex('};') + 1
PRACTICE_BANK = json.loads(content[idx:end_idx])

def mc(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"multiple_choice","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def ei(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"error_identification","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def st(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"sentence_transformation","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def comm(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"communication","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

# -------- TENSE 8: Hiện Tại Hoàn Thành Tiếp Diễn --------
PRACTICE_BANK["tense_8"] = {
  "round1": [
    mc("Hoàn thành câu: *\"She ________ for 3 hours and she's still not done.\"*<br>(Dịch: Cô ấy đã đang làm bài tập được 3 tiếng và vẫn chưa xong.)",
       {"A":"is studying","B":"has been studying","C":"has studied","D":"was studying"}, "B",
       "**B: has been studying**", "HTHTDT: S + has/have + been + V-ing (nhấn mạnh quá trình kéo dài đến nay).",
       "'3 hours' + 'still not done' → đang tiếp tục → HTHTDT.", "Dùng HTHT 'has studied' (kết quả đã xong, không còn đang làm).", "Đang còn tiếp tục + for + khoảng thời gian → HTHTDT!"),
    mc("Hoàn thành câu: *\"It ________ since early morning. The streets are all wet.\"*<br>(Dịch: Trời đã mưa từ sáng sớm. Đường xá đều ướt hết.)",
       {"A":"rains","B":"has rained","C":"has been raining","D":"rained"}, "C",
       "**C: has been raining**", "Kéo dài từ quá khứ đến nay với kết quả hiện tại rõ ràng → HTHTDT.",
       "Đường ướt (kết quả) + mưa từ sáng (quá trình) → HTHTDT.", "Dùng HTHT 'has rained' (nhấn mạnh kết quả, ít nhấn mạnh quá trình).", "Kết quả hiện tại + quá trình kéo dài → HTHTDT!"),
    mc("Hoàn thành câu: *\"How long ________ you ________ here?\"*<br>(Dịch: Bạn đã sống ở đây được bao lâu rồi?)",
       {"A":"did / live","B":"have / been living","C":"are / living","D":"have / lived"}, "B",
       "**B: have / been living**", "How long + HTHTDT: nhấn mạnh quá trình kéo dài.",
       "'How long' + đang còn ở → HTHTDT.", "Dùng HTHT 'have lived' (cũng đúng nhưng ít nhấn mạnh quá trình).", "How long + kéo dài đang còn → HTHTDT!"),
    mc("Hoàn thành câu: *\"I'm exhausted! I ________ all morning.\"*<br>(Dịch: Tôi kiệt sức! Tôi đã làm việc cả buổi sáng.)",
       {"A":"work","B":"was working","C":"have been working","D":"worked"}, "C",
       "**C: have been working**", "Kiệt sức = kết quả của quá trình kéo dài → HTHTDT.",
       "Mệt (hiện tại) vì làm suốt sáng (quá trình) → HTHTDT.", "QKĐ 'worked' (kết thúc, không liên hệ hiện tại).", "Mệt/bẩn/ướt bây giờ vì đang làm → HTHTDT!"),
    mc("Hoàn thành câu: *\"They ________ about the project for weeks but haven't reached a decision.\"*<br>(Dịch: Họ đã đang thảo luận về dự án nhiều tuần nhưng vẫn chưa đến quyết định.)",
       {"A":"discussed","B":"have discussed","C":"have been discussing","D":"are discussing"}, "C",
       "**C: have been discussing**", "Quá trình chưa hoàn thành → HTHTDT.",
       "Weeks + chưa có kết quả → quá trình chưa xong → HTHTDT.", "Dùng HTHT 'have discussed' (nhấn mạnh xong rồi).", "Chưa xong, đang tiếp tục → HTHTDT!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"Look at her eyes. She ________ for a long time.\"*<br>(Dịch: Nhìn mắt cô ấy kìa. Cô ấy đã khóc lâu rồi.)",
       {"A":"was crying","B":"has been crying","C":"cried","D":"is crying"}, "B",
       "**B: has been crying**", "Kết quả hiện tại (mắt đỏ) + quá trình → HTHTDT.",
       "Mắt đỏ = kết quả của quá trình khóc → HTHTDT.", "HTTD 'is crying' (đang khóc ngay lúc này).", "Kết quả thấy được ngay + quá trình vừa xong → HTHTDT!"),
    mc("Điền từ đúng: *\"He ________ English for 5 years and he speaks it fluently.\"*<br>(Dịch: Anh ấy học tiếng Anh được 5 năm và nói rất lưu loát.)",
       {"A":"learned","B":"has learned","C":"has been learning","D":"learns"}, "C",
       "**C: has been learning**", "Quá trình học 5 năm + kết quả nói tốt → HTHTDT.",
       "For 5 years + kết quả (speaks fluently) → HTHTDT.", "HTHT 'has learned' (cũng đúng nhưng ít nhấn mạnh quá trình).", "For + thời gian + kết quả → HTHTDT nhấn mạnh hành trình!"),
    mc("Điền từ đúng: *\"Why are your hands dirty? — I ________ the car.\"*<br>(Dịch: Tay bạn bẩn vì sao? - Tôi vừa sửa xe.)",
       {"A":"fix","B":"was fixing","C":"have been fixing","D":"fixed"}, "C",
       "**C: have been fixing**", "Giải thích kết quả hiện tại (tay bẩn) → HTHTDT.",
       "Tay bẩn = bằng chứng của quá trình vừa làm → HTHTDT.", "QKĐ 'fixed' (không giải thích tại sao tay bẩn ngay lúc này).", "Tay bẩn/ướt/mệt → HTHTDT giải thích nguyên nhân!"),
    mc("Điền từ đúng: *\"The kids ________ TV for hours. It's time to stop.\"*<br>(Dịch: Bọn trẻ đã xem TV mấy tiếng rồi. Đến lúc dừng thôi.)",
       {"A":"watch","B":"have been watching","C":"were watching","D":"have watched"}, "B",
       "**B: have been watching**", "Quá trình kéo dài (hours) → HTHTDT.",
       "Hours + vẫn đang làm → HTHTDT.", "HTHT 'have watched' (đã xong, nhấn mạnh kết quả).", "Hours kéo dài + chưa dừng → HTHTDT!"),
    mc("Điền từ đúng: *\"I ________ all day, so I need to get some rest.\"*<br>(Dịch: Tôi đã làm việc cả ngày rồi, cần nghỉ ngơi.)",
       {"A":"worked","B":"am working","C":"have been working","D":"work"}, "C",
       "**C: have been working**", "Quá trình liên tục suốt ngày → cần nghỉ → HTHTDT.",
       "All day + cần nghỉ → quá trình vừa kết thúc/đang kéo dài → HTHTDT.", "HTTD 'am working' (đang làm ngay lúc này, không nói về cả ngày).", "All day/all morning → HTHTDT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He has been write this novel for two years.\"*",
       {"A":"He has been writing this novel for two years.","B":"He has written this novel for two years.","C":"He is writing this novel for two years.","D":"He was writing this novel for two years."}, "A",
       "**A** là câu đúng.", "has been + V-ing: 'write' phải thêm -ing.",
       "'has been write' thiếu -ing → sai cú pháp.", "Dùng HTHT 'has written' (nhấn mạnh hoàn thành).", "Has been + V-ing (không phải V nguyên thể)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"They have been knew each other since childhood.\"*",
       {"A":"They have known each other since childhood.","B":"They have been knowing each other since childhood.","C":"They knew each other since childhood.","D":"They are knowing each other since childhood."}, "A",
       "**A** là câu đúng.", "'Know' = State Verb → KHÔNG dùng -ing, dùng HTHT.",
       "Know là động từ trạng thái → HTHT (have known), không phải HTHTDT.", "Giữ 'been knowing' (State Verb không dùng tiếp diễn).", "Know/understand/love → không bao giờ been knowing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She has been lived in Paris since 2010.\"*",
       {"A":"She has been living in Paris since 2010.","B":"She has lived in Paris since 2010.","C":"She have been living in Paris since 2010.","D":"She is living in Paris since 2010."}, "A",
       "**A** là câu đúng (nhấn mạnh quá trình).", "has been + V-ing: 'lived' phải thành 'living'.",
       "'has been lived' sai cú pháp (lived = V3, không phải V-ing).", "Dùng 'have' thay 'has' (C) — sai chủ ngữ She.", "Has been + V-ing (không phải V3)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"How long have they been waited for the bus?\"*",
       {"A":"How long have they been waiting for the bus?","B":"How long they have been waiting for the bus?","C":"How long have they wait for the bus?","D":"How long did they been waiting for the bus?"}, "A",
       "**A** là câu đúng.", "has/have been + V-ing: 'waited' → 'waiting'.",
       "'waited' = V3/V2, phải dùng V-ing = 'waiting'.", "Đảo sai trật tự (B).", "Have been + V-ing (động từ thêm -ing, không phải -ed/V3)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I have been knowing her for many years.\"*",
       {"A":"I have known her for many years.","B":"I am knowing her for many years.","C":"I knew her for many years.","D":"I has known her for many years."}, "A",
       "**A** là câu đúng.", "'Know' = State Verb → HTHT (have known), không phải HTHTDT.",
       "Động từ trạng thái không bao giờ dùng tiếp diễn.", "Giữ 'been knowing'.", "Know = State Verb → Have KNOWN, không phải been knowing!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She started teaching here 10 years ago and she's still teaching.\"*",
       {"A":"She has been teaching here for 10 years.","B":"She has taught here for 10 years.","C":"She was teaching here for 10 years.","D":"She taught here for 10 years."}, "A",
       "**A** là đúng nhất (nhấn mạnh quá trình).", "Bắt đầu QK + đang còn tiếp tục → HTHTDT.",
       "Vẫn đang dạy → quá trình chưa kết thúc → HTHTDT.", "HTHT 'has taught' (nhấn mạnh kết quả, ít nhấn mạnh đang còn tiếp tục).", "Đang còn tiếp tục → HTHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"Why is she so tired? Because she was running for an hour.\"*",
       {"A":"She has been running for an hour, that's why she's tired.","B":"She ran for an hour, that's why she's tired.","C":"She is running for an hour, that's why she's tired.","D":"She has run for an hour, that's why she's tired."}, "A",
       "**A** là đúng nhất.", "Kết quả hiện tại (tired) + quá trình vừa kéo dài → HTHTDT.",
       "Mệt ngay bây giờ vì đang chạy → HTHTDT giải thích.", "HTHT 'has run' (kết quả, ít nhấn mạnh quá trình gây mệt).", "Mệt ngay bây giờ VÌ làm gì = HTHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"I haven't finished the report. I started it 3 hours ago.\"*",
       {"A":"I have been working on the report for 3 hours.","B":"I have worked on the report for 3 hours.","C":"I worked on the report 3 hours ago.","D":"I was working on the report 3 hours ago."}, "A",
       "**A** là đúng nhất.", "Chưa xong + 3 tiếng → HTHTDT.",
       "Đang làm trong 3 tiếng và chưa xong → HTHTDT.", "HTHT 'have worked' (có thể đã xong).", "Chưa xong + đang tiếp tục → HTHTDT!"),
    comm("**Tình huống:** Bạn gặp lại người bạn cũ và muốn hỏi họ đã làm gì từ lần gặp nhau. Câu nào tự nhiên nhất?",
       {"A":"What have you been doing since we last met?","B":"What have you done since we last met?","C":"What were you doing since we last met?","D":"What did you do since we last met?"}, "A",
       "**A** là tự nhiên nhất.", "Hỏi về quá trình liên tục từ thời điểm QK → HTHTDT.",
       "Since we last met + what have you been up to → HTHTDT.", "HTHT 'what have you done' (ít nhấn mạnh quá trình).", "Since + điểm QK → HTHTDT khi hỏi về quá trình!"),
    comm("**Tình huống:** Bạn về nhà thấy anh/chị đang đứng ở phòng bếp, xung quanh đầy đồ nấu nướng. Bạn hỏi họ đang làm gì. Họ muốn trả lời: 'Tôi nấu bếp suốt 2 tiếng rồi!' Câu nào đúng?",
       {"A":"I have been cooking for 2 hours!","B":"I have cooked for 2 hours!","C":"I am cooking for 2 hours!","D":"I was cooking for 2 hours!"}, "A",
       "**A** là đúng nhất.", "Đang còn đứng đó + quá trình 2 tiếng → HTHTDT.",
       "Vẫn đang trong bếp (chưa nghỉ) + 2 tiếng → HTHTDT.", "HTHT 'have cooked' (đã xong, không còn đứng nấu).", "Vẫn đang làm + for + thời gian = HTHTDT!"),
  ]
}

# -------- TENSE 9: Quá Khứ Hoàn Thành Tiếp Diễn --------
PRACTICE_BANK["tense_9"] = {
  "round1": [
    mc("Hoàn thành câu: *\"She was exhausted because she ________ all day.\"*<br>(Dịch: Cô ấy kiệt sức vì đã làm việc cả ngày.)",
       {"A":"worked","B":"has worked","C":"had been working","D":"was working"}, "C",
       "**C: had been working**", "QKHTDT: nhấn mạnh quá trình liên tục trước một thời điểm QK.",
       "Kiệt sức (QK) vì làm suốt ngày (trước đó, liên tục) → QKHTDT.", "Dùng QKTD 'was working' (không nhấn mạnh tính hoàn thành trước).", "Mệt/bẩn trong QK VÌ làm liên tục → QKHTDT!"),
    mc("Hoàn thành câu: *\"He ________ for 2 hours when the bus finally arrived.\"*<br>(Dịch: Anh ấy đã đợi 2 tiếng thì xe buýt mới đến.)",
       {"A":"waited","B":"has been waiting","C":"had been waiting","D":"was waiting"}, "C",
       "**C: had been waiting**", "QKHTDT: quá trình liên tục trước thời điểm QK khác.",
       "Đợi (2h liên tục) → rồi xe đến (QKĐ) → QKHTDT.", "QKTD 'was waiting' (không nhấn mạnh khoảng thời gian).", "For + thời gian + trước QKĐ → QKHTDT!"),
    mc("Hoàn thành câu: *\"By the time I got to the office, it ________ for an hour.\"*<br>(Dịch: Lúc tôi đến văn phòng, cuộc họp đã diễn ra được 1 tiếng rồi.)",
       {"A":"had been going on","B":"was going on","C":"has been going on","D":"went on"}, "A",
       "**A: had been going on**", "QKHTDT: quá trình trước thời điểm QK (I got).",
       "Tôi đến (QKĐ) → cuộc họp đã bắt đầu 1h trước → QKHTDT.", "QKTD 'was going on' (không nhấn mạnh thời gian đã trôi qua).", "By the time + QKĐ → QKHTDT!"),
    mc("Hoàn thành câu: *\"They were tired because they ________ the whole night.\"*<br>(Dịch: Họ mệt vì đã thức cả đêm.)",
       {"A":"studied","B":"have studied","C":"had been studying","D":"are studying"}, "C",
       "**C: had been studying**", "QKHTDT: giải thích nguyên nhân của trạng thái QK.",
       "Mệt (QK) vì học suốt đêm (liên tục trước đó) → QKHTDT.", "QKĐ 'studied' (không nhấn mạnh tính liên tục).", "Mệt trong QK VÌ → QKHTDT!"),
    mc("Hoàn thành câu: *\"She ________ for the marathon for months before she got injured.\"*<br>(Dịch: Cô ấy đã luyện tập cho cuộc đua nhiều tháng trước khi bị thương.)",
       {"A":"trained","B":"was training","C":"had been training","D":"has trained"}, "C",
       "**C: had been training**", "Months liên tục → rồi bị thương (QKĐ) → QKHTDT.",
       "For months + trước khi bị thương → QKHTDT.", "QKTD (không nhấn mạnh khoảng thời gian liên tục).", "For months + before QKĐ → QKHTDT!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"I knew the city well because I ________ there for years.\"*",
       {"A":"lived","B":"have lived","C":"had been living","D":"was living"}, "C",
       "**C: had been living**", "QKHTDT: giải thích kiến thức QK bằng quá trình liên tục trước đó.",
       "Biết thành phố tốt (QK) vì đã sống lâu (liên tục trước) → QKHTDT.", "QKĐ 'lived' (không nhấn mạnh tính liên tục dẫn đến kết quả).", "For + years + before = QKHTDT!"),
    mc("Điền từ đúng: *\"His hands were dirty because he ________ his motorbike.\"*",
       {"A":"repaired","B":"had been repairing","C":"has repaired","D":"was repairing"}, "B",
       "**B: had been repairing**", "Tay bẩn (QK) giải thích bằng quá trình liên tục → QKHTDT.",
       "Tay bẩn = kết quả hiện tại trong ngữ cảnh QK → QKHTDT.", "QKTD 'was repairing' (không nhấn mạnh quá trình liên tục gây kết quả).", "Kết quả QK + giải thích bằng quá trình → QKHTDT!"),
    mc("Điền từ đúng: *\"She ________ for so long that she couldn't stand up straight.\"*<br>(Dịch: Cô ấy đứng lâu đến mức không đứng thẳng được.)",
       {"A":"stood","B":"was standing","C":"had been standing","D":"has stood"}, "C",
       "**C: had been standing**", "Đứng lâu (liên tục, trước) → không thể đứng thẳng (QK) → QKHTDT.",
       "So long + result → QKHTDT.", "QKTD 'was standing' (không nhấn mạnh khoảng thời gian dẫn đến kết quả).", "So long that → QKHTDT!"),
    mc("Điền từ đúng: *\"They ________ for hours before they finally found the solution.\"*<br>(Dịch: Họ đã tranh luận nhiều tiếng mới tìm được giải pháp.)",
       {"A":"argued","B":"have argued","C":"had been arguing","D":"are arguing"}, "C",
       "**C: had been arguing**", "Tranh luận (hours, liên tục) → trước khi tìm ra (QKĐ) → QKHTDT.",
       "For hours + before found → QKHTDT.", "QKĐ 'argued' (không nhấn mạnh khoảng thời gian).", "For hours + before QKĐ → QKHTDT!"),
    mc("Điền từ đúng: *\"She felt sick because she ________ in the sun all afternoon.\"*<br>(Dịch: Cô ấy thấy không khỏe vì đã ngồi ngoài nắng cả buổi chiều.)",
       {"A":"sat","B":"had been sitting","C":"was sitting","D":"has sat"}, "B",
       "**B: had been sitting**", "Không khỏe (QK) vì ngồi nắng liên tục → QKHTDT.",
       "All afternoon (liên tục) → sick (kết quả QK) → QKHTDT.", "QKĐ 'sat' (không nhấn mạnh tính liên tục).", "All afternoon/all day → QKHTDT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She had been working when the phone rang.\"*",
       {"A":"Câu đúng, không cần sửa.", "B":"She was working when the phone rang.", "C":"She had worked when the phone rang.", "D":"She has been working when the phone rang."}, "A",
       "**A: Câu đúng**, không cần sửa.", "QKHTDT có thể dùng để mô tả hành động liên tục bị gián đoạn.",
       "Had been working (QKHTDT) + when rang (QKĐ) — đúng ngữ pháp.", "Muốn sửa thành QKTD (B) — cũng đúng nhưng không sai câu gốc.", "Đôi khi câu đã đúng — không cần sửa!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He had been waited for two hours before the doctor saw him.\"*",
       {"A":"He had been waiting for two hours before the doctor saw him.","B":"He has been waiting for two hours before the doctor saw him.","C":"He was waiting for two hours before the doctor saw him.","D":"He had waited for two hours before the doctor saw him."}, "A",
       "**A** là câu đúng.", "had been + V-ing: 'waited' → 'waiting'.",
       "'waited' = V2/V3, phải dùng V-ing = 'waiting'.", "Dùng HTHTDT 'has been waiting' (sai thì).", "Had been + V-ing (không phải -ed/V3)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"They have been practicing for hours before the show started.\"*",
       {"A":"They had been practicing for hours before the show started.","B":"They were practicing for hours before the show started.","C":"They had practiced for hours before the show started.","D":"They have practiced for hours before the show started."}, "A",
       "**A** là câu đúng.", "Trước QKĐ (started) + hours → QKHTDT (had been V-ing).",
       "Show started = QKĐ → trước đó dùng QKHTDT, không phải HTHTDT.", "Dùng QKHT (had practiced) — đúng nhưng ít nhấn mạnh quá trình.", "Before QKĐ → QKHTDT (had been V-ing)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"My eyes hurt because I had been stared at the screen.\"*",
       {"A":"My eyes hurt because I had been staring at the screen.","B":"My eyes hurt because I have been staring at the screen.","C":"My eyes hurt because I was staring at the screen.","D":"My eyes hurt because I stared at the screen."}, "A",
       "**A** là câu đúng.", "had been + V-ing: 'stared' → 'staring'.",
       "'stared' = V2/V3, phải là V-ing = 'staring'.", "Dùng HTHTDT 'have been staring' (sai thì — hurt ở QK).", "Had been + V-ing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"The ground was wet because it had been rained all night.\"*",
       {"A":"The ground was wet because it had been raining all night.","B":"The ground was wet because it has been raining all night.","C":"The ground was wet because it had rained all night.","D":"The ground was wet because it was raining all night."}, "A",
       "**A** là câu đúng.", "had been + V-ing: 'rained' → 'raining'.",
       "'had been rained' dùng V3 sai → phải là V-ing 'raining'.", "Dùng HTHTDT 'has been raining' (sai thì, ground was = QK).", "Had been + V-ing (không phải V3)!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She started writing the essay 3 hours before she finished it.\"*",
       {"A":"She had been writing the essay for 3 hours when she finally finished it.","B":"She was writing the essay for 3 hours when she finished it.","C":"She has been writing the essay for 3 hours when she finished it.","D":"She wrote the essay for 3 hours when she finished it."}, "A",
       "**A** là đúng nhất.", "3 tiếng liên tục → rồi xong (QKĐ) → QKHTDT.",
       "For 3 hours + before finished = QKHTDT.", "QKTD (B) — ít nhấn mạnh khoảng thời gian.", "For + thời gian + before QKĐ = QKHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"He was tired because of the long run.\"*",
       {"A":"He had been running for a long time, so he was tired.","B":"He ran for a long time, so he was tired.","C":"He has been running for a long time, so he was tired.","D":"He was running for a long time, so he was tired."}, "A",
       "**A** là đúng nhất.", "Mệt (QK) + giải thích bằng quá trình liên tục → QKHTDT.",
       "Chạy lâu (liên tục) → mệt → QKHTDT giải thích nguyên nhân.", "QKĐ 'ran' (ít nhấn mạnh tính liên tục).", "Mệt trong QK VÌ chạy lâu → QKHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"By the time she arrived, the others had already waited for 30 minutes.\"*",
       {"A":"When she arrived, the others had been waiting for 30 minutes.","B":"When she arrived, the others waited for 30 minutes.","C":"When she arrived, the others have been waiting for 30 minutes.","D":"When she arrived, the others were waiting for 30 minutes."}, "A",
       "**A** là đúng nhất.", "30 phút đợi liên tục + rồi cô ấy đến → QKHTDT.",
       "By the time = When; for 30 minutes liên tục trước → QKHTDT.", "QKTD 'were waiting' (không nhấn mạnh khoảng thời gian).", "When + QKĐ + for + thời gian → QKHTDT!"),
    comm("**Tình huống:** Bạn hỏi người bạn tại sao anh ấy trông mệt như vậy ở buổi học buổi chiều. Anh ấy giải thích rằng anh ấy đã không ngủ cả đêm vì làm bài tập. Câu trả lời nào đúng nhất?",
       {"A":"I had been doing homework all night, so I'm tired.","B":"I have been doing homework all night, so I'm tired.","C":"I was doing homework all night, so I'm tired.","D":"I did homework all night, so I'm tired."}, "B",
       "**B** là tự nhiên nhất khi nói với ai đó ngay lúc đó (liên hệ hiện tại).", "Kết quả hiện tại (mệt bây giờ) + quá trình → HTHTDT.",
       "Đang mệt ngay bây giờ vì làm suốt đêm → HTHTDT (liên hệ hiện tại).", "QKHTDT (A) — đúng nếu đang kể chuyện quá khứ.", "Mệt BÂY GIỜ vì làm suốt đêm → HTHTDT!"),
    comm("**Tình huống:** Trong một câu chuyện kể lại bằng QK, nhân vật giải thích tại sao anh ấy biết rất nhiều về thị trường chứng khoán khi gặp nhà đầu tư. Câu nào đúng nhất?",
       {"A":"He knew a lot because he had been studying the market for years.","B":"He knew a lot because he has been studying the market for years.","C":"He knew a lot because he was studying the market for years.","D":"He knew a lot because he studied the market for years."}, "A",
       "**A** là đúng nhất (ngữ cảnh kể chuyện QK).", "Biết (QK) vì học lâu liên tục (trước đó) → QKHTDT.",
       "Kể chuyện QK: knew (QK) + giải thích bằng quá trình trước → QKHTDT.", "HTHTDT 'has been studying' (sai thì khi toàn câu ở QK).", "Kể chuyện QK: knew VÌ had been studying!"),
  ]
}

# -------- TENSE 10 & 11: Tương Lai Tiếp Diễn & Tương Lai Hoàn Thành --------
PRACTICE_BANK["tense_10"] = {
  "round1": [
    mc("Hoàn thành câu: *\"At 9 AM tomorrow, she ________ a presentation to the board.\"*<br>(Dịch: Lúc 9 giờ sáng mai, cô ấy sẽ đang trình bày cho hội đồng.)",
       {"A":"gives","B":"will give","C":"will be giving","D":"is giving"}, "C",
       "**C: will be giving**", "Tương lai tiếp diễn: hành động đang diễn ra tại thời điểm TL.",
       "'At 9 AM tomorrow' = thời điểm cụ thể trong TL → TL tiếp diễn.", "TL đơn 'will give' (không thể hiện tính đang diễn ra).", "At + giờ cụ thể + tomorrow → TL tiếp diễn!"),
    mc("Hoàn thành câu: *\"This time next week, we ________ on the beach in Phu Quoc.\"*<br>(Dịch: Tuần sau vào giờ này, chúng ta đang nằm trên bãi biển Phú Quốc rồi.)",
       {"A":"lie","B":"will lie","C":"will be lying","D":"are lying"}, "C",
       "**C: will be lying**", "This time next week = thời điểm TL cụ thể → TL tiếp diễn.",
       "'This time next week' = điểm TL → đang làm gì → TL tiếp diễn.", "TL đơn 'will lie' (không thể hiện tính đang diễn ra).", "This time next week/month/year → TL tiếp diễn!"),
    mc("Hoàn thành câu: *\"By this time next year, she ________ her degree.\"*<br>(Dịch: Vào thời điểm này năm sau, cô ấy sẽ đã tốt nghiệp rồi.)",
       {"A":"will finish","B":"will be finishing","C":"will have finished","D":"finishes"}, "C",
       "**C: will have finished**", "By this time next year = mốc TL → TL hoàn thành.",
       "Mốc TL (này năm sau) → sẽ đã hoàn thành → TL hoàn thành.", "TL tiếp diễn 'will be finishing' (không thể hiện hoàn thành).", "By + mốc TL → Will have V3!"),
    mc("Hoàn thành câu: *\"Don't call me at 8. I ________ dinner.\"*<br>(Dịch: Đừng gọi lúc 8 giờ. Tôi đang ăn tối.)",
       {"A":"will eat","B":"will be eating","C":"am eating","D":"eat"}, "B",
       "**B: will be eating**", "Tại 8 giờ tối nay = thời điểm TL cụ thể → TL tiếp diễn.",
       "Lúc 8 giờ = thời điểm TL → TL tiếp diễn.", "TL đơn 'will eat' (sẽ ăn, nhưng không rõ đang ăn tại thời điểm đó).", "At + giờ + TL → TL tiếp diễn!"),
    mc("Hoàn thành câu: *\"By the time you finish reading this, I ________ this chapter.\"*<br>(Dịch: Khi bạn đọc xong cái này, tôi sẽ đã viết xong chương này rồi.)",
       {"A":"write","B":"will write","C":"will be writing","D":"will have written"}, "D",
       "**D: will have written**", "By the time + HTĐ → TL hoàn thành.",
       "'By the time you finish' = mốc TL → TL hoàn thành.", "TL tiếp diễn 'will be writing' (không thể hiện hoàn thành trước mốc).", "By the time + HTĐ → Will have V3!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"In five years' time, she ________ as a doctor for two years.\"*<br>(Dịch: Trong năm năm nữa, cô ấy sẽ đã làm bác sĩ được hai năm.)",
       {"A":"will work","B":"will be working","C":"will have worked","D":"has worked"}, "C",
       "**C: will have worked**", "In five years' time = mốc TL → TL hoàn thành.",
       "Mốc TL cụ thể + for two years → TL hoàn thành.", "TL tiếp diễn (B) không thể hiện hoàn thành trước mốc.", "In X years' time → Will have V3!"),
    mc("Điền từ đúng: *\"At midnight tonight, the spaceship ________ the earth's atmosphere.\"*<br>(Dịch: Lúc nửa đêm nay, tàu vũ trụ đang bay qua khí quyển Trái Đất.)",
       {"A":"leaves","B":"will leave","C":"will be leaving","D":"is leaving"}, "C",
       "**C: will be leaving**", "At midnight tonight = thời điểm TL → TL tiếp diễn.",
       "Thời điểm cụ thể trong TL + đang làm → TL tiếp diễn.", "TL đơn 'will leave' (không thể hiện đang diễn ra).", "At + thời điểm cụ thể + TL → TL tiếp diễn!"),
    mc("Điền từ đúng: *\"By the end of this month, they ________ their new product.\"*<br>(Dịch: Vào cuối tháng này, họ sẽ đã ra mắt sản phẩm mới.)",
       {"A":"launch","B":"will launch","C":"will have launched","D":"are launching"}, "C",
       "**C: will have launched**", "By the end of this month = mốc TL → TL hoàn thành.",
       "By + mốc TL → TL hoàn thành.", "TL đơn 'will launch' (không nhấn mạnh hoàn thành trước mốc).", "By + mốc TL → Will have V3!"),
    mc("Điền từ đúng: *\"I promise I ________ here when you get back.\"*<br>(Dịch: Tôi hứa tôi sẽ vẫn đang ở đây khi bạn quay lại.)",
       {"A":"will wait","B":"will be waiting","C":"am waiting","D":"wait"}, "B",
       "**B: will be waiting**", "TL tiếp diễn: nhấn mạnh đang chờ tại thời điểm bạn về.",
       "When you get back = thời điểm TL → đang chờ → TL tiếp diễn.", "TL đơn 'will wait' (không thể hiện đang diễn ra khi bạn về).", "Khi ai về = thời điểm TL → TL tiếp diễn!"),
    mc("Điền từ đúng: *\"She ________ this university for 4 years by the time she graduates.\"*<br>(Dịch: Cô ấy sẽ đã học tại trường này được 4 năm khi tốt nghiệp.)",
       {"A":"attended","B":"will attend","C":"will have attended","D":"will be attending"}, "C",
       "**C: will have attended**", "By the time + HTĐ → TL hoàn thành.",
       "By the time she graduates = mốc TL → TL hoàn thành.", "TL tiếp diễn (D) không thể hiện hoàn thành.", "By the time + HTĐ → Will have V3!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"At this time tomorrow, I will working from home.\"*",
       {"A":"At this time tomorrow, I will be working from home.","B":"At this time tomorrow, I am working from home.","C":"At this time tomorrow, I will worked from home.","D":"At this time tomorrow, I will work from home."}, "A",
       "**A** là câu đúng.", "TL tiếp diễn: will be + V-ing.",
       "'will working' thiếu 'be' → sai cú pháp.", "Dùng TL đơn 'will work' (không thể hiện đang diễn ra).", "Will + BE + V-ing = TL tiếp diễn!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By next month, we will finish the project.\"* (Muốn nhấn mạnh sẽ hoàn thành trước mốc)",
       {"A":"By next month, we will have finished the project.","B":"By next month, we will be finishing the project.","C":"By next month, we finished the project.","D":"By next month, we have finished the project."}, "A",
       "**A** là câu đúng.", "By + mốc TL → TL hoàn thành (will have V3).",
       "By next month = mốc TL → TL hoàn thành.", "TL tiếp diễn 'will be finishing' (không thể hiện hoàn thành).", "By + mốc TL → Will HAVE V3!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"This time next year, she will have been studying in Australia.\"*",
       {"A":"This time next year, she will be studying in Australia.","B":"This time next year, she studies in Australia.","C":"This time next year, she will have studied in Australia.","D":"This time next year, she is studying in Australia."}, "A",
       "**A** là câu đúng.", "This time next year = thời điểm TL cụ thể → TL tiếp diễn.",
       "Đang học tại thời điểm đó (không nhấn mạnh hoàn thành) → TL tiếp diễn.", "TL hoàn thành (C) phù hợp khi muốn nói đã xong.", "This time + TL = TL tiếp diễn (will be V-ing)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By the time he arrives, the meeting will starting.\"*",
       {"A":"By the time he arrives, the meeting will have started.","B":"By the time he arrives, the meeting will be starting.","C":"By the time he arrives, the meeting starts.","D":"By the time he arrives, the meeting started."}, "A",
       "**A** là câu đúng.", "By the time + HTĐ → TL hoàn thành.",
       "Anh ta đến = mốc TL → cuộc họp đã bắt đầu (trước đó) → TL hoàn thành.", "'will be starting' sai cú pháp ('will starting').", "By the time + HTĐ → Will have V3!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"In 10 years, electric cars will be replace most petrol cars.\"*",
       {"A":"In 10 years, electric cars will have replaced most petrol cars.","B":"In 10 years, electric cars will be replacing most petrol cars.","C":"In 10 years, electric cars will replace most petrol cars.","D":"In 10 years, electric cars replaced most petrol cars."}, "B",
       "**B** là câu đúng nhất (quá trình đang xảy ra).", "TL tiếp diễn: will be + V-ing.",
       "'will be replace' sai cú pháp → phải là 'will be replacing'.", "TL hoàn thành (A) — cũng có thể chấp nhận.", "Will be + V-ing = TL tiếp diễn!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She expects to finish her PhD by next June.\"*",
       {"A":"She will have finished her PhD by next June.","B":"She will finish her PhD by next June.","C":"She is finishing her PhD by next June.","D":"She finishes her PhD by next June."}, "A",
       "**A** là đúng nhất.", "By + mốc TL → TL hoàn thành.",
       "Expects to finish → sẽ đã xong trước mốc → TL hoàn thành.", "TL đơn 'will finish' (không nhấn mạnh hoàn thành trước mốc).", "Expects to finish by X = Will have V3 by X!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She will be on vacation this time next week, so don't email her.\"*",
       {"A":"This time next week, she will be enjoying her vacation.","B":"This time next week, she will enjoy her vacation.","C":"This time next week, she is on vacation.","D":"This time next week, she has been on vacation."}, "A",
       "**A** là đúng nhất.", "This time next week = thời điểm TL → TL tiếp diễn.",
       "On vacation (đang diễn ra) tại thời điểm TL cụ thể → TL tiếp diễn.", "TL đơn 'will enjoy' (không thể hiện đang diễn ra).", "This time + TL = đang làm → TL tiếp diễn!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The company will complete 100 projects before the year ends.\"*",
       {"A":"The company will have completed 100 projects by the end of the year.","B":"The company will complete 100 projects at the end of the year.","C":"The company is completing 100 projects by the end of the year.","D":"The company completes 100 projects before the year ends."}, "A",
       "**A** là đúng nhất.", "Before the year ends = by the end of the year → TL hoàn thành.",
       "Before + HTĐ = by + danh từ thời gian → TL hoàn thành.", "TL đơn (B) — không nhấn mạnh hoàn thành trước.", "Before/by + mốc TL → Will have V3!"),
    comm("**Tình huống:** Bạn muốn nói với bạn bè rằng khi họ đến thăm, bạn đang nấu ăn nên đừng làm phiền. Câu nào đúng nhất?",
       {"A":"When you arrive, I will be cooking dinner.","B":"When you arrive, I will cook dinner.","C":"When you arrive, I cook dinner.","D":"When you arrive, I am cooking dinner."}, "A",
       "**A** là đúng nhất.", "Khi họ đến = thời điểm TL → đang nấu → TL tiếp diễn.",
       "When you arrive (HTĐ TL) + đang làm → TL tiếp diễn.", "TL đơn 'will cook' (không thể hiện đang diễn ra).", "When + HTĐ = thời điểm TL → TL tiếp diễn!"),
    comm("**Tình huống:** Sếp hỏi bạn liệu dự án có xong kịp trước cuối tháng không. Bạn tự tin đảm bảo. Câu nào chuyên nghiệp nhất?",
       {"A":"Yes, we will have completed it by the end of the month.","B":"Yes, we will complete it by the end of the month.","C":"Yes, we are going to complete it by the end of the month.","D":"Yes, we will be completing it by the end of the month."}, "A",
       "**A** là chuyên nghiệp và chính xác nhất.", "By the end of the month = mốc TL → TL hoàn thành.",
       "TL hoàn thành nhấn mạnh sẽ hoàn tất trước mốc → chuyên nghiệp.", "TL đơn (B) — ít nhấn mạnh hơn.", "Cam kết hoàn thành TRƯỚC mốc → Will have V3!"),
  ]
}

# -------- TENSE 11: Tương Lai Hoàn Thành Tiếp Diễn --------
PRACTICE_BANK["tense_11"] = {
  "round1": [
    mc("Hoàn thành câu: *\"By 2030, scientists ________ on this cure for 20 years.\"*<br>(Dịch: Đến 2030, các nhà khoa học sẽ đã nghiên cứu phương thuốc này được 20 năm.)",
       {"A":"will work","B":"will have been working","C":"will be working","D":"will have worked"}, "B",
       "**B: will have been working**", "By + mốc TL + for + khoảng thời gian → TL hoàn thành tiếp diễn.",
       "By 2030 (mốc TL) + for 20 years (khoảng liên tục) → TLHTDT.", "TL hoàn thành 'will have worked' (không nhấn mạnh quá trình liên tục).", "By + mốc TL + for + khoảng thời gian = TLHTDT!"),
    mc("Hoàn thành câu: *\"By next month, she ________ here for a year.\"*<br>(Dịch: Vào tháng sau, cô ấy sẽ đã làm việc ở đây được một năm.)",
       {"A":"will work","B":"will have worked","C":"will have been working","D":"will be working"}, "C",
       "**C: will have been working**", "By + mốc TL + for + khoảng thời gian = TLHTDT.",
       "By next month (mốc) + for a year (liên tục) → TLHTDT.", "TL hoàn thành (B) — ít nhấn mạnh quá trình liên tục.", "For + thời gian + by + mốc TL = TLHTDT!"),
    mc("Hoàn thành câu: *\"By the time we reach Rome, we ________ for 12 hours.\"*<br>(Dịch: Khi chúng ta đến Rome, chúng ta sẽ đã đi được 12 tiếng.)",
       {"A":"will travel","B":"will have traveled","C":"will be traveling","D":"will have been traveling"}, "D",
       "**D: will have been traveling**", "By the time + HTĐ + for + khoảng thời gian = TLHTDT.",
       "By the time we reach (mốc TL) + for 12 hours (liên tục) → TLHTDT.", "TL hoàn thành (B) — ít nhấn mạnh quá trình.", "By the time + for → TLHTDT!"),
    mc("Hoàn thành câu: *\"In 2025, I ________ English for 10 years.\"*<br>(Dịch: Vào 2025, tôi sẽ đã học tiếng Anh được 10 năm.)",
       {"A":"will study","B":"will be studying","C":"will have been studying","D":"will have studied"}, "C",
       "**C: will have been studying**", "In 2025 (mốc) + for 10 years (khoảng liên tục) = TLHTDT.",
       "In 2025 + for 10 years → nhấn mạnh quá trình liên tục → TLHTDT.", "TL hoàn thành (D) — ít nhấn mạnh quá trình.", "In (mốc TL) + for (khoảng) = TLHTDT!"),
    mc("Hoàn thành câu: *\"By the time Tom retires, he ________ for the same company for 35 years.\"*<br>(Dịch: Khi Tom về hưu, anh ấy sẽ đã làm cho cùng một công ty được 35 năm.)",
       {"A":"will work","B":"will have been working","C":"will be working","D":"will have worked"}, "B",
       "**B: will have been working**", "By the time + for 35 years liên tục → TLHTDT.",
       "35 năm liên tục (nhấn mạnh quá trình) + mốc TL → TLHTDT.", "TL hoàn thành (D) — ít nhấn mạnh quá trình.", "By the time + for + 35 years = TLHTDT!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"When she turns 30, she ________ in the army for 10 years.\"*",
       {"A":"will serve","B":"will be serving","C":"will have been serving","D":"will have served"}, "C",
       "**C: will have been serving**", "When + HTĐ + for + thời gian = TLHTDT.",
       "When turns 30 (mốc TL) + for 10 years (liên tục) → TLHTDT.", "TL hoàn thành (D) — ít nhấn mạnh quá trình.", "When + HTĐ + for → TLHTDT!"),
    mc("Điền từ đúng: *\"By the end of this project, the team ________ together for 3 years.\"*",
       {"A":"will have been working","B":"will work","C":"will be working","D":"will have worked"}, "A",
       "**A: will have been working**", "By the end = mốc TL + for 3 years liên tục → TLHTDT.",
       "By the end (mốc) + for 3 years → TLHTDT.", "TL tiếp diễn (C) không thể hiện hoàn thành trước mốc.", "By + mốc + for → TLHTDT!"),
    mc("Điền từ đúng: *\"Next year, this school ________ for 100 years.\"*<br>(Dịch: Năm sau, trường này sẽ đã hoạt động được 100 năm.)",
       {"A":"will have been operating","B":"will operate","C":"will have operated","D":"will be operating"}, "A",
       "**A: will have been operating**", "Next year (mốc) + for 100 years (liên tục) → TLHTDT.",
       "100 năm liên tục + mốc TL → TLHTDT nhấn mạnh quá trình.", "TL hoàn thành (C) — ít nhấn mạnh quá trình liên tục.", "Mốc TL + for + 100 years = TLHTDT!"),
    mc("Điền từ đúng: *\"By the time he finishes his PhD, he ________ for 8 years.\"*",
       {"A":"will study","B":"will have been studying","C":"will be studying","D":"will have studied"}, "B",
       "**B: will have been studying**", "By the time + HTĐ + for 8 years → TLHTDT.",
       "8 năm liên tục học + mốc (finishes PhD) → TLHTDT.", "TL hoàn thành (D) — ít nhấn mạnh quá trình.", "By the time + for → TLHTDT!"),
    mc("Điền từ đúng: *\"At the end of this month, I ________ at this restaurant for 5 years.\"*",
       {"A":"will have worked","B":"will work","C":"will have been working","D":"am working"}, "C",
       "**C: will have been working**", "At the end of this month + for 5 years → TLHTDT.",
       "5 năm liên tục + mốc TL (end of month) → TLHTDT.", "TL hoàn thành (A) — đúng nhưng ít nhấn mạnh quá trình.", "At the end + for → TLHTDT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By 2025, he will have been wait for this opportunity for 10 years.\"*",
       {"A":"By 2025, he will have been waiting for this opportunity for 10 years.","B":"By 2025, he will have waited for this opportunity for 10 years.","C":"By 2025, he will be waiting for this opportunity for 10 years.","D":"By 2025, he has been waiting for this opportunity for 10 years."}, "A",
       "**A** là câu đúng.", "will have been + V-ing: 'wait' → 'waiting'.",
       "'will have been wait' thiếu -ing.", "Dùng TL hoàn thành (B) — ít nhấn mạnh quá trình.", "Will have been + V-ing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By next year, they will worked on this project for 2 years.\"*",
       {"A":"By next year, they will have been working on this project for 2 years.","B":"By next year, they will work on this project for 2 years.","C":"By next year, they are working on this project for 2 years.","D":"By next year, they worked on this project for 2 years."}, "A",
       "**A** là câu đúng.", "By + mốc TL + for → will have been V-ing.",
       "'will worked' sai hoàn toàn — phải dùng TL hoàn thành (tiếp diễn).", "TL đơn 'will work' (B).", "By + TL + for = Will have been V-ing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"When he retires next year, he will have working here for 30 years.\"*",
       {"A":"When he retires next year, he will have been working here for 30 years.","B":"When he retires next year, he will work here for 30 years.","C":"When he retires next year, he will be working here for 30 years.","D":"When he retires next year, he worked here for 30 years."}, "A",
       "**A** là câu đúng.", "will have been + V-ing: 'working' đúng nhưng thiếu 'been'.",
       "'will have working' thiếu 'been' → sai cú pháp.", "TL tiếp diễn (C) không thể hiện hoàn thành trước mốc.", "Will HAVE BEEN V-ing (đủ 3 từ)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By the time you read this, I will have been left.\"*",
       {"A":"By the time you read this, I will have left.","B":"By the time you read this, I will be leaving.","C":"By the time you read this, I will have been leaving.","D":"By the time you read this, I have left."}, "A",
       "**A** là câu đúng.", "Leave không thể dùng TLHTDT (không phải hành động liên tục); TL hoàn thành là đúng.",
       "Leave = hành động đơn giản (không kéo dài liên tục) → TL hoàn thành (will have left).", "Dùng TLHTDT 'will have been leaving' (không phù hợp với leave).", "Leave/arrive/find = hành động đơn → TL hoàn thành, không phải tiếp diễn!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By the time this year ends, she will have been taught English for 15 years.\"*",
       {"A":"By the time this year ends, she will have been teaching English for 15 years.","B":"By the time this year ends, she will have taught English for 15 years.","C":"By the time this year ends, she will be teaching English for 15 years.","D":"By the time this year ends, she taught English for 15 years."}, "A",
       "**A** là câu đúng.", "TLHTDT chủ động: will have been teaching (không phải taught/being taught).",
       "'taught' sau been = bị động → sai với ngữ nghĩa chủ động (she is teacher).", "TL hoàn thành (B) — đúng nhưng ít nhấn mạnh quá trình.", "Chủ động + liên tục → Will have been TEACHING!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"They started the project 2 years ago. They plan to finish in 1 more year.\"*",
       {"A":"By next year, they will have been working on the project for 3 years.","B":"By next year, they will work on the project for 3 years.","C":"By next year, they will have worked on the project for 3 years.","D":"By next year, they are working on the project for 3 years."}, "A",
       "**A** là đúng nhất (nhấn mạnh quá trình liên tục).", "Tổng 3 năm liên tục + mốc TL → TLHTDT.",
       "2 năm đã qua + 1 năm nữa = 3 năm liên tục → TLHTDT.", "TL hoàn thành (C) — ít nhấn mạnh quá trình.", "Tổng thời gian liên tục + mốc = TLHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She has been learning French since 2019. By 2025 it will be 6 years.\"*",
       {"A":"By 2025, she will have been learning French for 6 years.","B":"By 2025, she will learn French for 6 years.","C":"By 2025, she will have learned French for 6 years.","D":"By 2025, she will be learning French for 6 years."}, "A",
       "**A** là đúng nhất.", "Đang học (liên tục) + mốc TL 2025 + for 6 years → TLHTDT.",
       "Học liên tục từ 2019 đến 2025 (6 năm) → TLHTDT nhấn mạnh quá trình.", "TL hoàn thành (C) — đúng nhưng ít nhấn mạnh.", "Đang học liên tục đến mốc TL → TLHTDT!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The company has run for 50 years. It will celebrate the 50th anniversary next year.\"*",
       {"A":"By its 50th anniversary next year, the company will have been running for 50 years.","B":"By its 50th anniversary next year, the company will run for 50 years.","C":"By its 50th anniversary next year, the company will be running for 50 years.","D":"By its 50th anniversary next year, the company will have run for 50 years."}, "A",
       "**A** là đúng nhất (nhấn mạnh quá trình liên tục).", "50 năm liên tục + mốc TL → TLHTDT.",
       "50 năm hoạt động (liên tục) + mốc (anniversary) → TLHTDT.", "TL hoàn thành (D) — ít nhấn mạnh quá trình.", "50 năm liên tục + by mốc = TLHTDT!"),
    comm("**Tình huống:** Bạn tự hào khoe với bạn bè rằng vào năm 2030, bạn sẽ đã học guitar được đúng 10 năm. Câu nào đúng nhất?",
       {"A":"By 2030, I will have been playing guitar for 10 years.","B":"By 2030, I will have played guitar for 10 years.","C":"By 2030, I will play guitar for 10 years.","D":"By 2030, I will be playing guitar for 10 years."}, "A",
       "**A** là đúng nhất (nhấn mạnh quá trình liên tục).", "10 năm liên tục + by mốc = TLHTDT.",
       "Nhấn mạnh hành trình 10 năm không bỏ → TLHTDT.", "TL hoàn thành (B) — ít mang tính 'hành trình'.", "Tự hào về hành trình liên tục → TLHTDT!"),
    comm("**Tình huống:** Công ty sắp kỷ niệm 20 năm thành lập. Giám đốc muốn phát biểu: 'Vào ngày kỷ niệm, chúng ta sẽ đã cùng nhau xây dựng công ty này được 20 năm.' Câu nào phù hợp nhất?",
       {"A":"By the anniversary, we will have been building this company together for 20 years.","B":"By the anniversary, we will have built this company together for 20 years.","C":"By the anniversary, we will build this company together for 20 years.","D":"By the anniversary, we will be building this company together for 20 years."}, "A",
       "**A** là phù hợp nhất (nhấn mạnh quá trình chung).", "20 năm liên tục + by mốc kỷ niệm → TLHTDT.",
       "Nhấn mạnh hành trình xây dựng 20 năm → TLHTDT.", "TL hoàn thành (B) — ít mang tính hành trình gắn kết.", "Hành trình liên tục + by mốc = TLHTDT!"),
  ]
}

print("tense_8-11 added!")
for k in ["tense_8","tense_9","tense_10","tense_11"]:
    v = PRACTICE_BANK[k]
    print(f"  {k}: R1={len(v['round1'])}, R2={len(v['round2'])}, R3={len(v['round3'])}")

output_path = '/Users/danghong/Documents/Exam Runners/website/js/practice_bank.js'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED PRACTICE BANK v2.0 — Chuẩn DAC A5.D\n')
    f.write('// Vòng 1: ≥5 câu Multiple Choice | Vòng 2: ≥10 câu (Cloze+Error ID) | Vòng 3: ≥5 câu (Transform+Comm)\n')
    f.write(f'const PRACTICE_BANK = {json.dumps(PRACTICE_BANK, indent=2, ensure_ascii=False)};\n')
print(f"Total keys: {len(PRACTICE_BANK)}")
