import json

# Load existing bank
with open('/Users/danghong/Documents/Exam Runners/website/js/practice_bank.js', 'r', encoding='utf-8') as f:
    content = f.read()
idx = content.index('const PRACTICE_BANK = ') + len('const PRACTICE_BANK = ')
end_idx = content.rindex('};') + 1
PRACTICE_BANK = json.loads(content[idx:end_idx])

def mc(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"multiple_choice","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def ei(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"error_identification","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def st(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"sentence_transformation","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}
def comm(stem, opts, correct, verdict, rule, why, trap, tip):
    return {"type":"communication","stem":stem,"options":opts,"correct":correct,
            "explanation":{"verdict":verdict,"rule":rule,"why":why,"trap":trap,"tip":tip}}

# -------- TENSE 4: Quá Khứ Tiếp Diễn --------
PRACTICE_BANK["tense_4"] = {
  "round1": [
    mc("Hoàn thành câu: *\"At 8 PM last night, I ________ for the exam.\"*<br>(Dịch: Lúc 8 giờ tối qua, tôi đang ôn thi.)",
       {"A":"study","B":"was studying","C":"studied","D":"were studying"}, "B",
       "**B: was studying**", "QKTD: S + was/were + V-ing (tại thời điểm cụ thể trong QK).",
       "'At 8 PM last night' = thời điểm xác định trong QK; 'I' → 'was'.", "Dùng 'studied' (QKĐ, không có tính tiếp diễn).", "At + giờ + last night → QKTD!"),
    mc("Hoàn thành câu: *\"The children ________ in the park when it started to rain.\"*<br>(Dịch: Các em bé đang chơi ở công viên thì trời bắt đầu mưa.)",
       {"A":"played","B":"were playing","C":"was playing","D":"are playing"}, "B",
       "**B: were playing**", "Hành động đang diễn ra (QKTD) khi bị xen vào (QKĐ).",
       "'When it started' = QKĐ xen vào; 'children' số nhiều → 'were playing'.", "Dùng 'was playing' (sai hòa hợp chủ-vị).", "Đang làm (QKTD) thì việc khác xảy ra (QKĐ)!"),
    mc("Hoàn thành câu: *\"While my mom ________ dinner, my dad ________ the news.\"*<br>(Dịch: Trong khi mẹ tôi đang nấu bữa tối, bố tôi đang xem tin tức.)",
       {"A":"cooked / watched","B":"was cooking / was watching","C":"was cooking / watched","D":"cooking / watching"}, "B",
       "**B: was cooking / was watching**", "While + 2 QKTD = Hai hành động song song cùng lúc.",
       "Cả hai đều đang diễn ra đồng thời → cả hai QKTD.", "Một vế QKĐ và một vế QKTD (C) — sai khi muốn diễn tả đồng thời.", "While + QKTD, QKTD = song song cùng lúc!"),
    mc("Hoàn thành câu: *\"I ________ TV when my phone rang.\"*<br>(Dịch: Tôi đang xem TV thì điện thoại reo.)",
       {"A":"was watching","B":"watched","C":"am watching","D":"were watching"}, "A",
       "**A: was watching**", "Hành động đang diễn ra (QKTD) bị gián đoạn bởi QKĐ.",
       "Phone rang = QKĐ xen vào; đang xem TV = QKTD; 'I' → 'was'.", "Dùng QKĐ cho cả hai → mất tính đang tiếp diễn.", "Rang xen vào → was watching bị gián đoạn!"),
    mc("Hoàn thành câu: *\"She ________ at this company for years before she got promoted.\"*<br>(Dịch: Cô ấy đã làm việc ở công ty này nhiều năm trước khi được thăng chức.)",
       {"A":"has worked","B":"is working","C":"had been working","D":"was working"}, "C",
       "**C: had been working**", "QKHT tiếp diễn: nhấn mạnh quá trình kéo dài trước một thời điểm QK khác.",
       "Trước khi thăng chức (QK) → kéo dài liên tục trước đó → QKHT tiếp diễn.", "Dùng QKTD 'was working' (không thể hiện tính hoàn thành trước thời điểm QK).", "Kéo dài TRƯỚC một thời điểm QK → QKHT tiếp diễn (had been V-ing)!"),
  ],
  "round2": [
    mc("Điền từ đúng vào chỗ trống:<br>*\"The student ________ when the teacher entered the room.\"*<br>(Dịch: Học sinh đang nói chuyện khi giáo viên bước vào.)",
       {"A":"was talking","B":"talked","C":"talks","D":"has talked"}, "A",
       "**A: was talking**", "QKTD đang diễn ra bị QKĐ xen vào.",
       "Teacher entered (QKĐ) xen vào đang nói chuyện (QKTD).", "Dùng QKĐ 'talked' (không nắm bắt tính đang diễn ra).", "QKTD (đang diễn ra) + khi + QKĐ (xen vào)!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"What ________ you ________ this time yesterday?\"*<br>(Dịch: Bạn đang làm gì vào giờ này hôm qua?)",
       {"A":"are / doing","B":"were / doing","C":"did / do","D":"was / doing"}, "B",
       "**B: were / doing**", "Câu hỏi QKTD: What were + S + V-ing?",
       "'This time yesterday' = thời điểm cụ thể trong QK; 'you' → 'were'.", "Dùng 'did/do' (QKĐ, không có tính tiếp diễn).", "This time yesterday → QKTD!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"They ________ so loudly in the next room that I couldn't concentrate.\"*<br>(Dịch: Họ đang nói chuyện ồn ào đến mức tôi không thể tập trung.)",
       {"A":"talked","B":"were talking","C":"are talking","D":"have talked"}, "B",
       "**B: were talking**", "QKTD diễn tả cản trở đang diễn ra trong QK.",
       "Đang nói ồn ào (liên tục, cản trở) → QKTD.", "QKĐ 'talked' không thể hiện tính liên tục gây bực.", "Hành động liên tục gây cản trở trong QK → QKTD!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"While she ________ the dishes, she broke a glass.\"*<br>(Dịch: Trong khi cô ấy đang rửa bát, cô ấy làm vỡ một chiếc ly.)",
       {"A":"was washing / broke","B":"washed / broke","C":"was washing / was breaking","D":"washes / broke"}, "A",
       "**A: was washing / broke**", "QKTD bị QKĐ xen vào.",
       "Đang rửa bát (QKTD) thì làm vỡ ly (QKĐ đột ngột).", "Cả hai QKĐ (B) mất tính 'đang làm trong khi'.", "While + QKTD, + QKĐ = bị xen vào!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"The band ________ for two hours before the power went out.\"*<br>(Dịch: Ban nhạc đang biểu diễn được hai tiếng thì mất điện.)",
       {"A":"played","B":"was playing","C":"had been playing","D":"is playing"}, "C",
       "**C: had been playing**", "Kéo dài cho đến trước một thời điểm QK khác → QKHT tiếp diễn.",
       "Biểu diễn 2 tiếng (liên tục) cho đến khi mất điện → had been playing.", "Dùng QKTD 'was playing' (không nhấn mạnh khoảng thời gian liên tục).", "for + thời gian + trước khi xảy ra → QKHT tiếp diễn!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He was watch TV when she called.\"*",
       {"A":"He was watching TV when she called.","B":"He is watching TV when she called.","C":"He watched TV when she called.","D":"He were watching TV when she called."}, "A",
       "**A** là câu đúng.", "QKTD: was + V-ing; 'watch' phải thêm -ing.",
       "'was watch' thiếu -ing → sai cú pháp.", "Đổi thì thành HTĐ (B) hoặc QKĐ (C).", "was/were + V-ing: không thể bỏ -ing!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"While I was walked to school, I found a wallet on the ground.\"*",
       {"A":"While I was walking to school, I found a wallet on the ground.","B":"While I walked to school, I was finding a wallet on the ground.","C":"While I was walked to school, I was finding a wallet on the ground.","D":"While I walk to school, I found a wallet on the ground."}, "A",
       "**A** là câu đúng.", "was + V-ing: 'walked' phải trở về 'walking'.",
       "'was walked' là dạng bị động, không phải QKTD tiếp diễn chủ động.", "Đảo lộn vai trò hai vế (B).", "QKTD chủ động: was/were + V-ing (không phải V3)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She were cooking when the guests arrived.\"*",
       {"A":"She was cooking when the guests arrived.","B":"She is cooking when the guests arrived.","C":"She was cook when the guests arrived.","D":"She been cooking when the guests arrived."}, "A",
       "**A** là câu đúng.", "'She' số ít → 'was' (không phải 'were').",
       "She/He/It → was; I → was; We/You/They → were.", "Dùng 'were' cho 'She'.", "She/He/It → WAS (không phải were)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"They was playing basketball when it began to rain.\"*",
       {"A":"They were playing basketball when it began to rain.","B":"They was play basketball when it began to rain.","C":"They is playing basketball when it began to rain.","D":"They were play basketball when it began to rain."}, "A",
       "**A** là câu đúng.", "They → were (không phải was).",
       "They/We/You → were; He/She/It/I → was.", "Dùng 'was' cho 'They'.", "They → WERE (không phải was)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"At midnight, I slept deeply, so I didn't hear the thunderstorm.\"*",
       {"A":"At midnight, I was sleeping deeply, so I didn't hear the thunderstorm.","B":"At midnight, I sleep deeply, so I didn't hear the thunderstorm.","C":"At midnight, I was sleep deeply, so I didn't hear the thunderstorm.","D":"At midnight, I have slept deeply, so I didn't hear the thunderstorm."}, "A",
       "**A** là câu đúng.", "At midnight = thời điểm xác định → QKTD (was sleeping).",
       "Lúc nửa đêm đang ngủ say → QKTD, không phải QKĐ kết thúc.", "Dùng QKĐ 'slept' (không nắm bắt tính đang diễn ra).", "At + giờ cụ thể + in the past → QKTD!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She was cooking dinner when her husband came home.\"*",
       {"A":"Her husband came home while she was cooking dinner.","B":"She cooked dinner when her husband came home.","C":"While her husband came home, she was cooking dinner.","D":"She had cooked dinner when her husband came home."}, "A",
       "**A** là đúng nhất.", "Đảo vế while/when — QKTD và QKĐ.",
       "Chỉ cần đổi trật tự hai mệnh đề, nghĩa không đổi.", "Dùng QKĐ cho cả hai (B) mất tính tiếp diễn.", "While QKTD / When QKĐ: có thể đảo vế không đổi nghĩa!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"It was raining when we left the house.\"*",
       {"A":"When we left the house, it was raining.","B":"When we left the house, it rained.","C":"While it rained, we were leaving the house.","D":"It rained when we were leaving the house."}, "A",
       "**A** là đúng nhất.", "QKTD (raining) đang diễn ra khi QKĐ (left) xảy ra.",
       "Chỉ đảo vị trí hai mệnh đề, thì động từ không đổi.", "Đổi 'was raining' thành 'rained' (B) làm mất tính đang diễn ra.", "Đảo vế = đổi thứ tự, không đổi thì!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"I was in the middle of writing an email when the power went off.\"*",
       {"A":"I was writing an email when the power went off.","B":"I wrote an email when the power went off.","C":"While the power went off, I write an email.","D":"I had been writing an email when the power went off."}, "A",
       "**A** là đồng nghĩa gần nhất.", "'In the middle of V-ing' = đang làm dở dang → QKTD.",
       "In the middle of = đang làm giữa chừng → QKTD.", "Dùng QKĐ 'wrote' (không nắm bắt tính dang dở).", "In the middle of V-ing = was V-ing (QKTD)!"),
    comm("**Tình huống:** Bạn muốn kể lại: 'Khi bắt đầu cháy, cả tòa nhà đang ngủ.' Câu nào đúng nhất?",
       {"A":"When the fire started, the whole building was sleeping.","B":"When the fire was starting, the whole building slept.","C":"While the whole building slept, the fire was starting.","D":"When the fire started, the whole building is sleeping."}, "A",
       "**A** là đúng nhất.", "Cháy (QKĐ, đột ngột) xen vào đang ngủ (QKTD).",
       "Fire started = QKĐ đột ngột; was sleeping = QKTD đang diễn ra.", "Đảo lộn: making 'starting' tiếp diễn (B).", "Sự kiện đột ngột (QKĐ) cắt ngang hành động đang diễn ra (QKTD)!"),
    comm("**Tình huống:** Cảnh sát hỏi nhân chứng: 'Bạn đang làm gì lúc 9 giờ tối thứ Sáu?' Câu trả lời nào đúng nhất?",
       {"A":"I was watching a movie at home with my family.","B":"I watched a movie at home with my family.","C":"I watch a movie at home with my family.","D":"I had watched a movie at home with my family."}, "A",
       "**A** là đúng nhất.", "Hỏi về hoạt động đang làm tại thời điểm cụ thể trong QK → QKTD.",
       "Câu hỏi 'What were you doing at 9 PM?' → 'I was V-ing'.", "QKĐ (B) không mô tả tính đang diễn ra liên tục tại thời điểm đó.", "Hỏi đang làm gì lúc X (QK) → QKTD!"),
  ]
}

# -------- TENSE 5: Quá Khứ Hoàn Thành --------
PRACTICE_BANK["tense_5"] = {
  "round1": [
    mc("Hoàn thành câu: *\"By the time we arrived, she ________ already ________.\"*<br>(Dịch: Khi chúng tôi đến nơi, cô ấy đã đi về rồi.)",
       {"A":"has / left","B":"had / left","C":"was / leaving","D":"have / left"}, "B",
       "**B: had / left**", "QKHT: S + had + V3 (xảy ra trước một thời điểm QK).",
       "'By the time we arrived' = thời điểm QK; cô ấy về trước đó → QKHT.", "Dùng HTHT 'has left' (sai thì, không liên hệ hiện tại).", "By the time + QKĐ → QKHT (had V3)!"),
    mc("Hoàn thành câu: *\"He had never ________ sushi before that trip to Japan.\"*<br>(Dịch: Anh ấy chưa bao giờ ăn sushi trước chuyến đi Nhật đó.)",
       {"A":"eat","B":"ate","C":"eaten","D":"eats"}, "C",
       "**C: eaten**", "QKHT + never: had never + V3.",
       "'had never + V3' → 'eaten' là V3 của 'eat'.", "Dùng 'ate' (V2, không dùng sau had).", "Had + V3 (cột 3)! Eaten không phải ate!"),
    mc("Hoàn thành câu: *\"She ________ the book three times before she watched the movie.\"*<br>(Dịch: Cô ấy đã đọc cuốn sách đó ba lần trước khi xem phim.)",
       {"A":"has read","B":"have read","C":"had read","D":"was reading"}, "C",
       "**C: had read**", "QKHT: hoàn thành trước một hành động QK khác.",
       "Đọc sách (3 lần) → trước → xem phim (QKĐ) → QKHT.", "Dùng HTHT 'has read' (sai thì, không liên hệ hiện tại).", "Xảy ra trước một QKĐ khác → QKHT (had V3)!"),
    mc("Hoàn thành câu: *\"After she ________ the letter, she felt much better.\"*<br>(Dịch: Sau khi cô ấy đọc bức thư, cô ấy cảm thấy tốt hơn nhiều.)",
       {"A":"read","B":"had read","C":"has read","D":"was reading"}, "B",
       "**B: had read**", "After + QKHT, + QKĐ = hoàn thành trước rồi kết quả sau.",
       "Đọc thư (before) → cảm thấy tốt hơn (after); 'after' + QKHT.", "Dùng QKĐ 'read' (hai lần QKĐ, mất trật tự thứ tự thời gian).", "After + QKHT → QKĐ (sau khi hoàn thành)!"),
    mc("Hoàn thành câu: *\"The team ________ hard all season, so they were disappointed to lose the final.\"*<br>(Dịch: Đội đã tập luyện chăm chỉ cả mùa, nên họ thất vọng khi thua trận chung kết.)",
       {"A":"trained","B":"has trained","C":"had trained","D":"was training"}, "C",
       "**C: had trained**", "Tập luyện (kéo dài, hoàn thành) trước kết quả thua → QKHT.",
       "Toàn bộ mùa giải (QK) → rồi thua → QKHT nhấn mạnh nỗ lực đã hoàn thành.", "Dùng QKĐ 'trained' (không nhấn mạnh tính hoàn thành trước).", "Nhấn mạnh hoàn thành trước kết quả QK → QKHT!"),
  ],
  "round2": [
    mc("Điền từ đúng vào chỗ trống:<br>*\"I realized I ________ my phone at home after I arrived at school.\"*",
       {"A":"left","B":"have left","C":"had left","D":"was leaving"}, "C",
       "**C: had left**", "Nhận ra (arrived) → nhưng bỏ quên đã xảy ra trước → QKHT.",
       "Bỏ quên (before) → nhận ra (after arriving) → QKHT.", "Dùng QKĐ 'left' (không rõ trật tự thời gian).", "Nhận ra trong QK + sự việc đã qua trước đó → QKHT!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"The movie ________ already ________ when we got to the cinema.\"*",
       {"A":"was / started","B":"had / started","C":"has / started","D":"is / starting"}, "B",
       "**B: had / started**", "Phim bắt đầu trước khi chúng ta đến → QKHT.",
       "We got = QKĐ; film started earlier → QKHT.", "Dùng HTHT 'has started'.", "Sự kiện QK xảy ra trước một QKĐ khác → QKHT!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"They ________ never ________ abroad before that business trip.\"*",
       {"A":"had / traveled","B":"have / traveled","C":"did / travel","D":"were / traveling"}, "A",
       "**A: had / traveled**", "Trước chuyến đi đó (QK) chưa bao giờ đi → QKHT.",
       "'Before that business trip' = mốc QK → trước đó → QKHT.", "Dùng HTHT (B) không đặt trong QK.", "Never + had + V3 + before (thời điểm QK)!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"She was exhausted because she ________ for 10 hours straight.\"*<br>(Dịch: Cô ấy kiệt sức vì đã học liên tục 10 tiếng.)",
       {"A":"studied","B":"has studied","C":"had been studying","D":"was studying"}, "C",
       "**C: had been studying**", "QKHT tiếp diễn: nhấn mạnh quá trình liên tục trước thời điểm QK.",
       "10 tiếng liên tục (quá trình) → dẫn đến kiệt sức → QKHT tiếp diễn.", "Dùng QKHT đơn 'had studied' (ít nhấn mạnh tính liên tục hơn).", "Kéo dài liên tục trước QK → had been V-ing!"),
    mc("Điền từ đúng vào chỗ trống:<br>*\"I felt guilty because I ________ to her.\"*<br>(Dịch: Tôi cảm thấy tội lỗi vì đã nói dối cô ấy.)",
       {"A":"lie","B":"lied","C":"had lied","D":"was lying"}, "C",
       "**C: had lied**", "Cảm thấy tội lỗi (QK) vì đã nói dối (trước đó) → QKHT.",
       "Nói dối xảy ra trước cảm giác tội lỗi → QKHT.", "QKĐ 'lied' (không rõ thứ tự thời gian).", "Nguyên nhân (QKHT) → Kết quả (QKĐ)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"After they had ate lunch, they went for a walk.\"*",
       {"A":"After they had eaten lunch, they went for a walk.","B":"After they have eaten lunch, they go for a walk.","C":"After they ate lunch, they have gone for a walk.","D":"After they ate lunch, they had gone for a walk."}, "A",
       "**A** là câu đúng.", "had + V3: 'ate' là V2, phải dùng V3 = 'eaten'.",
       "Sau had không dùng V2 (ate) mà dùng V3 (eaten).", "Đổi cả hai động từ sang thì khác.", "had + V3 (cột 3): had eaten, had gone, had done!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She told me that she has finished the project the day before.\"*",
       {"A":"She told me that she had finished the project the day before.","B":"She told me that she finished the project the day before.","C":"She tells me that she had finished the project the day before.","D":"She told me that she has finish the project the day before."}, "A",
       "**A** là câu đúng.", "Tường thuật QKĐ → Mệnh đề phụ lùi thì về QKHT.",
       "told (QKĐ) → has finished lùi thành had finished.", "Giữ nguyên 'has finished' (không lùi thì).", "Tường thuật: QKĐ → QKHT!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By the time the ambulance arrived, the patient has died.\"*",
       {"A":"By the time the ambulance arrived, the patient had died.","B":"By the time the ambulance arrives, the patient had died.","C":"By the time the ambulance arrived, the patient was died.","D":"By the time the ambulance arrived, the patient has been died."}, "A",
       "**A** là câu đúng.", "By the time + QKĐ → mệnh đề chính dùng QKHT.",
       "Bệnh nhân mất (trước) → xe cấp cứu đến (sau) → QKHT.", "Dùng 'was died' (bị động sai - die không dùng bị động).", "By the time + QKĐ → had V3!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He had never saw such a beautiful sunset before that evening.\"*",
       {"A":"He had never seen such a beautiful sunset before that evening.","B":"He never saw such a beautiful sunset before that evening.","C":"He has never saw such a beautiful sunset before that evening.","D":"He had never see such a beautiful sunset before that evening."}, "A",
       "**A** là câu đúng.", "had + V3: 'saw' là V2, phải dùng V3 = 'seen'.",
       "see → saw → seen; sau 'had' dùng 'seen'.", "Dùng 'see' (V1) sau 'had' (D).", "See → Saw → Seen! Sau had dùng Seen!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I didn't recognize her because she had changed so much.\"*",
       {"A":"Câu này đúng rồi, không có lỗi.", "B":"I didn't recognize her because she changed so much.", "C":"I didn't recognize her because she has changed so much.", "D":"I don't recognize her because she had changed so much."}, "A",
       "**A: Câu đúng, không cần sửa.**", "QKĐ (didn't recognize) + QKHT (had changed) = chuẩn trật tự thời gian.",
       "Thay đổi (trước) → không nhận ra (sau) — cấu trúc đúng.", "Muốn sửa khi câu đã đúng.", "Đôi khi câu đã đúng — không cần sửa!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She ate breakfast before she went to school.\"*",
       {"A":"Before she went to school, she had eaten breakfast.","B":"After she had gone to school, she ate breakfast.","C":"She has eaten breakfast before she goes to school.","D":"Before going to school, she eat breakfast."}, "A",
       "**A** là đúng nhất.", "Trước + QKĐ = đổi thành QKHT trong vế Before.",
       "Eat breakfast (trước) → go to school (sau) → thêm had vào before.", "Đảo lộn thứ tự (B).", "Trước một QKĐ → QKHT (had V3)!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"It was the first time I had tried bungee jumping.\"*",
       {"A":"I had never tried bungee jumping before.","B":"I have never tried bungee jumping before.","C":"I never try bungee jumping.","D":"I hadn't tried bungee jumping before."}, "A",
       "**A** là đúng nhất (ngữ cảnh QK).", "First time + QKHT = Had never + V3 + before.",
       "Lần đầu tiên (trong QK) = never had done before that moment.", "Dùng HTHT 'have never' (không đặt trong QK).", "First time (QK) + QKHT = Had never V3 before!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The thief escaped before the police arrived.\"*",
       {"A":"By the time the police arrived, the thief had escaped.","B":"The police arrived before the thief had escaped.","C":"When the police had arrived, the thief escaped.","D":"The thief escaped when the police arrive."}, "A",
       "**A** là đúng nhất.", "By the time + QKĐ = sự kiện đã hoàn thành trước (QKHT).",
       "Trốn thoát (before) → cảnh sát đến (after) → By the time + QKHT.", "Đảo lộn trật tự thời gian (B).", "By the time = Before (thời điểm), dùng QKHT!"),
    comm("**Tình huống:** Bạn kể với bạn bè: 'Trước khi xem phim Spider-Man mới nhất, mình đã xem toàn bộ các phim trước.' Câu nào đúng?",
       {"A":"I had watched all the previous films before I saw the latest Spider-Man.","B":"I have watched all the previous films before I saw the latest Spider-Man.","C":"I watched all the previous films before I see the latest Spider-Man.","D":"I had been watching all the previous films before I saw the latest Spider-Man."}, "A",
       "**A** là đúng nhất.", "Xem phim trước (QK xa) → xem phim mới (QK gần) → QKHT.",
       "Hoàn thành toàn bộ (trước) → xem mới (sau trong QK) → QKHT.", "Dùng HTHT 'have watched' (không đặt trong ngữ cảnh QK rõ ràng).", "Trước một hành động QK khác → QKHT!"),
    comm("**Tình huống:** Giáo viên hỏi học sinh tại sao không làm bài tập. Học sinh muốn giải thích: 'Em đã quên mang vở bài tập về nhà.' Câu nào đúng nhất?",
       {"A":"I had forgotten to bring my notebook home.","B":"I forgot to bring my notebook home.","C":"I have forgotten to bring my notebook home.","D":"I was forgetting to bring my notebook home."}, "B",
       "**B** là tự nhiên và đúng nhất trong giao tiếp.", "QKĐ đủ để giải thích trong ngữ cảnh này.",
       "Trong giao tiếp hàng ngày, QKĐ đủ rõ ràng. QKHT thêm nhấn mạnh nhưng không sai.", "Chỉ chấp nhận QKHT.", "Cả QKĐ và QKHT đều có thể dùng; QKĐ tự nhiên hơn trong giao tiếp!"),
  ]
}

# -------- TENSE 6: Tương Lai Đơn (will) --------
PRACTICE_BANK["tense_6"] = {
  "round1": [
    mc("Hoàn thành câu: *\"A: The phone is ringing! B: Don't worry, I ________ it.\"*<br>(Dịch: Để mặc anh, anh sẽ bắt máy.)",
       {"A":"am going to get","B":"get","C":"will get","D":"got"}, "C",
       "**C: will get**", "Will = quyết định tức thì ngay lúc nói.",
       "Quyết định bắt máy ngay lúc điện thoại reo → will.", "Dùng 'am going to get' (kế hoạch trước đó, không phải tức thì).", "Quyết định bộc phát ngay lúc nói → WILL!"),
    mc("Hoàn thành câu: *\"Scientists believe the global temperature ________ by 2 degrees by 2050.\"*<br>(Dịch: Các nhà khoa học tin nhiệt độ toàn cầu sẽ tăng 2 độ vào năm 2050.)",
       {"A":"rises","B":"will rise","C":"is going to rise","D":"rose"}, "B",
       "**B: will rise**", "Will = dự đoán/niềm tin về tương lai không có bằng chứng cụ thể.",
       "Scientists believe = ý kiến dự đoán → will.", "Dùng 'is going to rise' (cần bằng chứng cụ thể).", "Believe/think/hope + tương lai = Will!"),
    mc("Hoàn thành câu: *\"I promise I ________ you as soon as I arrive.\"*<br>(Dịch: Tôi hứa sẽ gọi cho bạn ngay khi đến nơi.)",
       {"A":"call","B":"am calling","C":"will call","D":"called"}, "C",
       "**C: will call**", "Lời hứa → Will.",
       "'I promise' = cam kết tương lai → will.", "Dùng HTTD 'am calling' (kế hoạch, không phải lời hứa).", "Promise/swear → Will!"),
    mc("Hoàn thành câu: *\"If you eat too much junk food, you ________ sick.\"*<br>(Dịch: Nếu bạn ăn quá nhiều đồ ăn vặt, bạn sẽ bị ốm.)",
       {"A":"get","B":"will get","C":"are getting","D":"got"}, "B",
       "**B: will get**", "ĐK loại 1: If + HTĐ, S + will + V-inf.",
       "Vế If chia HTĐ (eat), vế chính dùng will.", "Dùng HTĐ cho cả 2 vế (get).", "If + HTĐ → Will + V-inf!"),
    mc("Hoàn thành câu: *\"Wait here. I ________ be back in five minutes.\"*<br>(Dịch: Chờ đây nhé. Tôi sẽ trở lại trong 5 phút.)",
       {"A":"am going to","B":"will","C":"am","D":"going to"}, "B",
       "**B: will**", "Cam kết/khẳng định tức thì → will.",
       "Đây là lời cam kết ngắn gọn → will.", "Dùng 'am going to' (cần them 'be going to' đủ).", "Cam kết/đảm bảo → Will!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"A: I'm cold! B: I ________ the window.\"*<br>(Dịch: Để tôi đóng cửa sổ cho.)",
       {"A":"am going to close","B":"will close","C":"close","D":"am closing"}, "B",
       "**B: will close**", "Will = đề nghị giúp đỡ tức thì.",
       "Bạn mới nghe thấy lạnh ngay lúc đó → tức thì đề nghị giúp → will.", "Dùng 'am going to close' (kế hoạch từ trước).", "Đề nghị giúp đỡ tức thì → Will!"),
    mc("Điền từ đúng: *\"By this time tomorrow, we ________ over the Pacific Ocean.\"*<br>(Dịch: Vào giờ này ngày mai, chúng ta sẽ đang bay qua Thái Bình Dương.)",
       {"A":"will fly","B":"will be flying","C":"are flying","D":"will have flown"}, "B",
       "**B: will be flying**", "Tương lai tiếp diễn: hành động đang diễn ra tại thời điểm cụ thể trong TL.",
       "'By this time tomorrow' = thời điểm cụ thể trong TL → TL tiếp diễn.", "Dùng TL đơn 'will fly' (không thể hiện tính đang diễn ra).", "By this time + TL = Tương lai tiếp diễn (will be V-ing)!"),
    mc("Điền từ đúng: *\"Don't call her at 8 PM. She ________ the kids to bed.\"*<br>(Dịch: Đừng gọi lúc 8 tối. Cô ấy đang cho các con đi ngủ.)",
       {"A":"is putting","B":"puts","C":"will be putting","D":"will put"}, "C",
       "**C: will be putting**", "Hành động đang diễn ra tại thời điểm cụ thể trong TL → TL tiếp diễn.",
       "Lúc 8 PM tối mai = thời điểm TL, đang làm → will be putting.", "Dùng TL đơn 'will put' (không thể hiện tính đang diễn ra lúc đó).", "Thời điểm cụ thể + TL + đang làm → Will be V-ing!"),
    mc("Điền từ đúng: *\"By the end of the year, she ________ this company for 10 years.\"*<br>(Dịch: Đến cuối năm, cô ấy sẽ làm cho công ty này được 10 năm.)",
       {"A":"will work","B":"will be working","C":"will have worked","D":"has worked"}, "C",
       "**C: will have worked**", "Tương lai hoàn thành: sẽ hoàn thành trước mốc TL.",
       "'By the end of the year' = mốc TL → sẽ đã hoàn thành 10 năm → TL hoàn thành.", "Dùng TL đơn (A) không thể hiện tính hoàn thành trước mốc.", "By + mốc TL → Will have V3!"),
    mc("Điền từ đúng: *\"I think it ________ a great opportunity for you.\"*<br>(Dịch: Tôi nghĩ đây sẽ là một cơ hội tuyệt vời cho bạn.)",
       {"A":"is","B":"will be","C":"would be","D":"was"}, "B",
       "**B: will be**", "I think + dự đoán TL → will.",
       "'I think' = ý kiến về TL → will + V-inf.", "Dùng 'would be' (giả định, không phải dự đoán thực).", "Think/believe/hope + TL → Will!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"If you will study hard, you will pass the exam.\"*",
       {"A":"If you study hard, you will pass the exam.","B":"If you studied hard, you will pass the exam.","C":"If you will study hard, you would pass the exam.","D":"If you study hard, you would pass the exam."}, "A",
       "**A** là câu đúng.", "Mệnh đề If không được dùng will.",
       "Vế If dùng HTĐ (study), vế chính mới dùng will.", "Giữ 'will' trong vế If.", "Tuyệt đối không dùng WILL trong mệnh đề IF (điều kiện loại 1)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She will calls me when she arrives.\"*",
       {"A":"She will call me when she arrives.","B":"She will call me when she will arrive.","C":"She will calling me when she arrives.","D":"She calls me when she will arrive."}, "A",
       "**A** là câu đúng.", "Will + V-inf (nguyên thể, không chia).",
       "'calls' không dùng sau will; vế 'when' không dùng will.", "Thêm will vào vế when (B).", "Will + V (nguyên thể); When/before/after + HTĐ (không will)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I think she will be a good doctor because she care about people.\"*",
       {"A":"I think she will be a good doctor because she cares about people.","B":"I think she would be a good doctor because she cares about people.","C":"I think she will be a good doctor because she has cared about people.","D":"I think she will be a good doctor because she is caring about people."}, "A",
       "**A** là câu đúng.", "Mệnh đề because: thói quen hiện tại → HTĐ số ít (cares).",
       "'She care' thiếu -s vì số ít.", "Dùng HTHT hoặc HTTD không phù hợp.", "She/He/It + V-s/es trong HTĐ thói quen!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Will you please to stop making noise?\"*",
       {"A":"Will you please stop making noise?","B":"Will you please stopped making noise?","C":"Will you please to stopping making noise?","D":"Would you please to stop making noise?"}, "A",
       "**A** là câu đúng.", "Will you please + V-inf (không cần 'to').",
       "'Will you please + V' không dùng 'to' trước động từ.", "Dùng V-ed (B) sau will please.", "Will/Would you please + V (nguyên thể, không 'to')!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"By next month, we will completed the project.\"*",
       {"A":"By next month, we will have completed the project.","B":"By next month, we will be completing the project.","C":"By next month, we completed the project.","D":"By next month, we will complete the project."}, "A",
       "**A** là câu đúng.", "By + mốc TL → Tương lai hoàn thành (will have V3).",
       "'By next month' = mốc TL → sẽ hoàn thành trước đó → will have V3.", "Giữ 'will completed' (thiếu have).", "By + TL = Will HAVE V3!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"I'm sure it's going to be a success.\"*",
       {"A":"I'm sure it will be a success.","B":"I'm sure it was a success.","C":"I'm sure it would be a success.","D":"I'm sure it has been a success."}, "A",
       "**A** là đúng nhất.", "Be going to (chắc chắn) ≈ will (dự đoán/tin tưởng).",
       "Cả hai diễn đạt sự chắc chắn về tương lai.", "Dùng 'would be' (giả định).", "Going to và Will đều nói về TL; going to = chắc chắn hơn!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"The flight is scheduled to depart at 6 AM.\"*",
       {"A":"The flight will depart at 6 AM.","B":"The flight departs at 6 AM.","C":"The flight is departing at 6 AM.","D":"The flight is going to depart at 6 AM."}, "B",
       "**B** là đúng nhất.", "Lịch trình bay cố định → HTĐ.",
       "Lịch trình phương tiện công cộng → HTĐ, không phải will.", "Dùng will (A) không chuẩn cho lịch trình cố định.", "Lịch trình cố định → HTĐ!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"I am certain that she will win the competition.\"*",
       {"A":"There is no doubt that she will win the competition.","B":"I think she might win the competition.","C":"She would win the competition, I am certain.","D":"She wins the competition certainly."}, "A",
       "**A** là đúng nhất.", "Am certain = There is no doubt = chắc chắn.",
       "Cả hai thể hiện sự chắc chắn tương đương.", "Dùng 'might' (không chắc).", "I am certain = There is no doubt = I am sure!"),
    comm("**Tình huống:** Bạn đang ở cửa hàng cùng bạn, bạn lấy một cái áo lên xem. Bạn của bạn hỏi: 'Are you going to buy it?' Bạn muốn nói 'Mình không biết, mình sẽ suy nghĩ thêm.' Câu nào đúng nhất?",
       {"A":"I don't know, I will think about it.","B":"I don't know, I'm thinking about it.","C":"I don't know, I would think about it.","D":"I don't know, I thought about it."}, "A",
       "**A** là đúng nhất.", "Quyết định chưa có → Will (chưa quyết).",
       "I will think = tôi sẽ suy nghĩ (quyết định tức thì chưa mua).", "Dùng HTTD 'am thinking' (đang suy nghĩ ngay lúc này).", "I'll think about it = câu lịch sự để chưa quyết!"),
    comm("**Tình huống:** Bạn nghe dự báo thời tiết nói sẽ có bão. Bạn muốn cảnh báo người thân: 'Tuần này sẽ có bão lớn.' Câu nào phù hợp nhất?",
       {"A":"There will be a big storm this week.","B":"There would be a big storm this week.","C":"There is a big storm this week.","D":"There was a big storm this week."}, "A",
       "**A** là đúng nhất.", "Dự báo thời tiết TL → Will.",
       "Cảnh báo về bão sắp đến → will be (TL).", "Dùng HTĐ 'there is' (hiện tại).", "Cảnh báo/dự đoán → Will!"),
  ]
}

# -------- TENSE 7: Tương Lai Gần (be going to) --------
PRACTICE_BANK["tense_7"] = {
  "round1": [
    mc("Hoàn thành câu: *\"Watch out! You ________ fall!\"*<br>(Dịch: Coi chừng! Bạn sắp ngã rồi!)",
       {"A":"will","B":"are going to","C":"going to","D":"would"}, "B",
       "**B: are going to**", "Bằng chứng hiện tại rõ ràng → be going to.",
       "Thấy người sắp ngã ngay trước mắt → bằng chứng cụ thể → going to.", "Dùng 'will' (phỏng đoán không có bằng chứng).", "Bằng chứng nhìn thấy ngay → Going to!"),
    mc("Hoàn thành câu: *\"She ________ study medicine at university next year.\"* (Đã đăng ký rồi)<br>(Dịch: Cô ấy định học y khoa ở đại học năm sau.)",
       {"A":"will","B":"is going to","C":"studies","D":"going to"}, "B",
       "**B: is going to**", "Kế hoạch đã định sẵn → be going to.",
       "Đã đăng ký (đã có chuẩn bị) → going to.", "Dùng 'will' (quyết định tức thì).", "Kế hoạch có chuẩn bị trước → Be going to!"),
    mc("Hoàn thành câu: *\"Look at those black clouds. It ________ rain.\"*<br>(Dịch: Nhìn đám mây đen kia kìa. Trời sắp mưa rồi.)",
       {"A":"will","B":"is going to","C":"would","D":"rains"}, "B",
       "**B: is going to**", "Mây đen = bằng chứng hiện tại → going to.",
       "Bằng chứng trực quan → going to.", "Dùng 'will' (phỏng đoán mơ hồ).", "Bằng chứng thực tế → Going to (không phải will)!"),
    mc("Hoàn thành câu: *\"We ________ visit our grandparents this Sunday. (Đã lên lịch rồi)\"*<br>(Dịch: Chúng tôi định đến thăm ông bà Chủ nhật này.)",
       {"A":"will visit","B":"are going to visit","C":"visited","D":"visit"}, "B",
       "**B: are going to visit**", "Kế hoạch đã sắp xếp → be going to.",
       "Đã lên lịch trước → going to.", "Will = chưa quyết, mới nảy ra ý định.", "Lên lịch sẵn → Going to; Mới nảy ra → Will!"),
    mc("Hoàn thành câu: *\"He's been saving money for months. He ________ buy a new laptop.\"*<br>(Dịch: Anh ấy đã tiết kiệm nhiều tháng. Anh ấy định mua laptop mới.)",
       {"A":"will","B":"is going to","C":"buys","D":"bought"}, "B",
       "**B: is going to**", "Tiết kiệm tháng trước = chuẩn bị → going to.",
       "Đã chuẩn bị (tiết kiệm) → có kế hoạch rõ ràng → going to.", "Dùng 'will' (mới quyết ngay lúc đó).", "Chuẩn bị trước = Going to!"),
  ],
  "round2": [
    mc("Điền từ đúng: *\"A: Have you decided what to have for dinner? B: Yes, I ________ make pasta.\"*",
       {"A":"will","B":"am going to","C":"make","D":"would"}, "B",
       "**B: am going to**", "Đã quyết định trước → going to.",
       "Hỏi 'Have you decided' + đã quyết → going to.", "Dùng 'will' (nếu mới quyết ngay lúc đó).", "Đã quyết định → Going to; Mới quyết → Will!"),
    mc("Điền từ đúng: *\"She ________ pass the exam if she doesn't study harder.\"*<br>(Dịch: Cô ấy sắp trượt nếu không học chăm hơn.)",
       {"A":"won't","B":"isn't going to","C":"doesn't","D":"isn't"}, "B",
       "**B: isn't going to**", "Xu hướng hiện tại (không học) → dự đoán có căn cứ → going to.",
       "Bằng chứng: không học → dự đoán trượt → going to (phủ định).", "Dùng 'won't' (phỏng đoán không có bằng chứng).", "Căn cứ vào hiện tại → going to (phủ định = isn't/aren't going to)!"),
    mc("Điền từ đúng: *\"I ________ clean my room today. I've been putting it off for too long.\"*<br>(Dịch: Hôm nay tôi quyết dọn phòng. Tôi đã trì hoãn quá lâu rồi.)",
       {"A":"will","B":"am going to","C":"clean","D":"have cleaned"}, "B",
       "**B: am going to**", "Quyết định vững chắc đã cân nhắc → going to.",
       "Đã trì hoãn lâu + quyết định dứt khoát → going to.", "Dùng 'will' (quyết định tức thì không có suy nghĩ trước).", "Quyết định dứt khoát sau cân nhắc → Going to!"),
    mc("Điền từ đúng: *\"Are you ________ attend the wedding next week?\"*<br>(Dịch: Bạn có định dự đám cưới tuần sau không?)",
       {"A":"will","B":"going to","C":"going","D":"to"}, "B",
       "**B: going to**", "Câu hỏi kế hoạch: Are + S + going to + V?",
       "Cấu trúc đầy đủ: Are you going to + V.", "Dùng 'will' (sai cấu trúc câu hỏi going to).", "Are/Is/Am + S + going to + V?"),
    mc("Điền từ đúng: *\"This bag is too heavy. I ________ drop it!\"*<br>(Dịch: Túi này nặng quá. Tôi sắp làm rơi rồi!)",
       {"A":"will drop","B":"am going to drop","C":"drop","D":"am dropping"}, "B",
       "**B: am going to drop**", "Cảm nhận ngay lúc đó = bằng chứng → going to.",
       "Cảm thấy nặng, sắp rơi ngay → bằng chứng → going to.", "Dùng 'will drop' (phỏng đoán, không có bằng chứng tức thì).", "Cảm nhận sắp xảy ra ngay = Going to!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"She going to visit her aunt this weekend.\"*",
       {"A":"She is going to visit her aunt this weekend.","B":"She are going to visit her aunt this weekend.","C":"She will going to visit her aunt this weekend.","D":"She goes to visit her aunt this weekend."}, "A",
       "**A** là câu đúng.", "Be going to: thiếu 'is' → she IS going to.",
       "'She' số ít → 'is going to'.", "Dùng 'are' cho 'she'.", "She + IS going to (không phải are)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Are they going to came to the party?\"*",
       {"A":"Are they going to come to the party?","B":"Are they going to comes to the party?","C":"Will they going to come to the party?","D":"Do they going to come to the party?"}, "A",
       "**A** là câu đúng.", "Going to + V-inf: 'came' phải về 'come'.",
       "Sau going to dùng V nguyên thể, không phải V2.", "Dùng 'comes' (thêm -s).", "Going to + V nguyên thể (không chia)!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"He isn't going to didn't come.\"*",
       {"A":"He isn't going to come.","B":"He is going to not come.","C":"He isn't going not to come.","D":"He doesn't going to come."}, "A",
       "**A** là câu đúng.", "Phủ định: S + isn't/aren't + going to + V-inf.",
       "Câu gốc dùng hai phủ định lồng nhau — sai hoàn toàn.", "Để 'not' giữa 'going' và 'to' (B).", "Phủ định Going to: isn't/aren't going to + V!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"Look at those dark clouds. It will rain.\"* (Bạn đang nhìn thấy mây đen)",
       {"A":"Look at those dark clouds. It is going to rain.","B":"Look at those dark clouds. It rains.","C":"Look at those dark clouds. It was going to rain.","D":"Look at those dark clouds. It would rain."}, "A",
       "**A** là câu đúng.", "Bằng chứng hiện tại (mây đen) → Going to, không phải will.",
       "Nhìn thấy mây đen ngay trước mắt → bằng chứng → going to.", "Dùng 'will' (không có bằng chứng cụ thể).", "Thấy bằng chứng ngay → Going to! Will = phỏng đoán!"),
    ei("Câu sau có một lỗi sai. Hãy chọn phương án sửa đúng nhất:<br>*\"I am going to studied medicine next year.\"*",
       {"A":"I am going to study medicine next year.","B":"I will going to study medicine next year.","C":"I am going to studying medicine next year.","D":"I go to study medicine next year."}, "A",
       "**A** là câu đúng.", "Going to + V-inf: 'studied' phải về 'study'.",
       "Sau going to dùng V nguyên thể, không phải V2 hay V-ing.", "Dùng V-ing 'studying' (C).", "Going to + V nguyên thể (không -ing, không -ed)!"),
  ],
  "round3": [
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"There are signs that the economy is recovering.\"*",
       {"A":"The economy is going to recover.","B":"The economy will recover.","C":"The economy recovers.","D":"The economy would recover."}, "A",
       "**A** là đúng nhất.", "Dấu hiệu hiện tại → going to (dự đoán có căn cứ).",
       "'Signs' = bằng chứng → going to.", "Dùng 'will' (không có bằng chứng).", "Có dấu hiệu/bằng chứng → Going to!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"My plan is to open a coffee shop after graduation.\"*",
       {"A":"I am going to open a coffee shop after graduation.","B":"I will open a coffee shop after graduation.","C":"I open a coffee shop after graduation.","D":"I was going to open a coffee shop after graduation."}, "A",
       "**A** là đúng nhất.", "Kế hoạch cá nhân đã định → going to.",
       "My plan = kế hoạch đã có → going to.", "Dùng 'will' (quyết định mới).", "My plan = I am going to!"),
    st("Chọn câu **đồng nghĩa** với câu sau:<br>*\"She has decided to quit her job.\"*",
       {"A":"She is going to quit her job.","B":"She will quit her job.","C":"She quits her job.","D":"She has been going to quit her job."}, "A",
       "**A** là đúng nhất.", "Đã quyết định = kế hoạch → going to.",
       "Has decided = đã có quyết định → going to.", "Dùng 'will' (mới quyết).", "Has decided → Going to!"),
    comm("**Tình huống:** Bạn thấy một đứa trẻ cầm ly nước và đang nghiêng người ra cạnh bàn. Bạn muốn cảnh báo mẹ nó. Câu nào đúng?",
       {"A":"The child is going to spill the water!","B":"The child will spill the water!","C":"The child spills the water!","D":"The child would spill the water!"}, "A",
       "**A** là đúng nhất.", "Thấy ngay trước mắt = bằng chứng → going to.",
       "Nhìn thấy đứa bé đang nghiêng → bằng chứng → going to.", "Dùng 'will' (phỏng đoán không bằng chứng).", "Thấy ngay trước mắt → Going to!"),
    comm("**Tình huống:** Bạn hỏi người bạn đã có dự định gì cho kỳ nghỉ hè. Câu hỏi nào tự nhiên nhất?",
       {"A":"What are you going to do this summer?","B":"What will you do this summer?","C":"What do you do this summer?","D":"What did you do this summer?"}, "A",
       "**A** là tự nhiên nhất khi hỏi về kế hoạch đã có.", "Going to = hỏi về kế hoạch đã lên.",
       "What are you going to do? = kế hoạch trước.", "What will you do? = tự nhiên hơn khi hỏi mơ hồ.", "Hỏi kế hoạch đã có → Going to; Hỏi chung chung → Will!"),
  ]
}

print("tense_4-7 added!")
for k in ["tense_4","tense_5","tense_6","tense_7"]:
    v = PRACTICE_BANK[k]
    print(f"  {k}: R1={len(v['round1'])}, R2={len(v['round2'])}, R3={len(v['round3'])}")

# Write to file
output_path = '/Users/danghong/Documents/Exam Runners/website/js/practice_bank.js'
with open(output_path, 'w', encoding='utf-8') as f:
    f.write('// AUTO-GENERATED PRACTICE BANK v2.0 — Chuẩn DAC A5.D\n')
    f.write('// Vòng 1: ≥5 câu Multiple Choice | Vòng 2: ≥10 câu (Cloze+Error ID) | Vòng 3: ≥5 câu (Transform+Comm)\n')
    f.write(f'const PRACTICE_BANK = {json.dumps(PRACTICE_BANK, indent=2, ensure_ascii=False)};\n')
print("Written to practice_bank.js")
